### ISSUE TITLE
Can't see SharePoint connector

### ISSUE THREAD

**Issue by aagirre92** [danswer-ai/danswer#1008]
Hi! I am deploying the latest version of this using docker-compose.dev.yml but I cannot see any reference to **SharePoint connector**. Is this available? I can't see it:

![image](https://github.com/danswer-ai/danswer/assets/70752869/8e52982b-734a-4185-9350-6b7ab96321ae)

**Comment by Weves** [comment]
Hey @aagirre92, if you pull in the latest it should be visible!
