### ISSUE TITLE
SharePoint - No documents are indexed if pointing to a specific site

### ISSUE THREAD

**Issue by aagirre92** [danswer-ai/danswer#1017]
Hello there!

I have been testing the SharePoint connector capabilities and I see that no docs are indexed if you set up the connector to a specific site (e.g. https://<tenant>.sharepoint.com/sites/<site-name>). In this site (in Documents) I have 26 .docx files and none is indexed

![image](https://github.com/danswer-ai/danswer/assets/70752869/cd6ba683-f8cb-47a4-8f53-eb1f78969c63)

**Comment by fan-wen** [comment]
You need to only input the site name instead of the full site address
![image](https://github.com/danswer-ai/danswer/assets/25698512/a004f788-fd6b-4f9a-b722-548c269413ea)

**Comment by aagirre92** [comment]
That was it sorry! I thought I needed to put full site url
