### ISSUE TITLE
AUTH_TYPE=basic, new registered users could not login

### ISSUE THREAD

**Issue by dami2010** [danswer-ai/danswer#1022]
AUTH_TYPE=basic, new user could register successfully. But when the user try to login with email and password, it always show the login page with no error. 
When I check the log information on api-server, I can see following information:
NFO:     172.18.0.7:33528 - "POST /auth/login HTTP/1.1" 204 No Content
INFO:     172.18.0.6:48192 - "GET /auth/type HTTP/1.1" 200 OK
INFO:     172.18.0.6:48198 - "GET /manage/me HTTP/1.1" 403 Forbidden
INFO:     172.18.0.6:48204 - "GET /manage/connector HTTP/1.1" 403 Forbidden
INFO:     172.18.0.6:48248 - "GET /secondary-index/get-current-embedding-model HTTP/1.1" 403 Forbidden
INFO:     172.18.0.6:48216 - "GET /manage/document-set HTTP/1.1" 403 Forbidden
INFO:     172.18.0.6:48232 - "GET /persona HTTP/1.1" 403 Forbidden
INFO:     172.18.0.6:48236 - "GET /query/valid-tags HTTP/1.1" 403 Forbidden
INFO:     172.18.0.6:48192 - "GET /manage/me HTTP/1.1" 403 Forbidden
INFO:     172.18.0.7:33542 - "GET /health HTTP/1.1" 200 OK
INFO:     172.18.0.7:40466 - "GET /health HTTP/1.1" 200 OK

Pls let me know how to handle it. Many thanks!

**Comment by im-calvin** [comment]
Having the same issue, let me know if you find a fix

**Comment by Weves** [comment]
Hey @dami2010 and @im-calvin! Are you all setting things up with `https` or just plain `http`? Or just running things locally?

**Comment by im-calvin** [comment]
Hi @Weves. At the moment I'm running the development server (with a `.env` file) locally with `http`.

**Comment by FangxuY** [comment]
Hi @Weves, could you please provide a solution that in plain http or just running things locally?

**Comment by Weves** [comment]
Hey @FangxuY, I'm not able to re-create the issue 🤔 When I run things locally without https, it works as expected. 

Can you post your `.env` file?

**Comment by FangxuY** [comment]
Thanks @Weves for your attention. Actually I do not have `.env` file. Here is my `deployment/docker-compose` directory:

<img width="335" alt="image" src="https://github.com/danswer-ai/danswer/assets/48797491/ed838029-035b-452f-8df9-0f6ecc86cf48">

I followed https://docs.danswer.dev/quickstart to deploy it (`docker compose -f docker-compose.dev.yml -p danswer-stack up -d --build --force-recreate`) in my Ubuntu server and want to add a basic auth step.

If I need a `.env` file, How should I set it? Thanks for your time!

**Comment by abbaasi** [comment]
I have the same problem here.
Setting up thing locally with http.
here is my .env file:
`GEN_AI_MODEL_PROVIDER=azure
GEN_AI_MODEL_VERSION=xxxx  # Note that this is the Azure Deployment ID
GEN_AI_API_ENDPOINT=https://xxxxxxx.openai.azure.com/
GEN_AI_API_VERSION=2024-02-15-preview
GEN_AI_API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxx
AUTH_TYPE=basic
`
The signup does not give any message, but it seems the users are registered.
But when logging in, it gives the following error:
t/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36" "-"
api_server-1     | INFO:     172.18.0.6:36540 - "GET /auth/type HTTP/1.1" 200 OK
api_server-1     | INFO:     172.18.0.6:36548 - "GET /manage/me HTTP/1.1" 403 Forbidden
api_server-1     | INFO:     172.18.0.6:36584 - "GET /secondary-index/get-embedding-models HTTP/1.1" 403 Forbidden
api_server-1     | INFO:     172.18.0.6:36552 - "GET /manage/indexing-status HTTP/1.1" 403 Forbidden
api_server-1     | INFO:     172.18.0.6:36578 - "GET /query/valid-tags HTTP/1.1" 403 Forbidden
api_server-1     | INFO:     172.18.0.6:36566 - "GET /manage/document-set HTTP/1.1" 403 Forbidden
api_server-1     | INFO:     172.18.0.6:36574 - "GET /persona HTTP/1.1" 403 Forbidden
nginx-1          | 151.240.162.111 - - [27/Feb/2024:10:20:07 +0000] "GET /search HTTP/1.1" 200 875 "http://20.220.168.122:3000/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36" "-"
api_server-1     | INFO:     172.18.0.6:36540 - "GET /manage/me HTTP/1.1" 403 Forbidden

**Comment by im-calvin** [comment]
@abbaasi Seems like the website requires HTTPS to work properly. I suggest creating a self-signed certificate or something of that nature and making sure that you're on HTTPS. Should resolve all your issues 🤞
