### ISSUE TITLE
 How to access DAnswer through an API interface?

### ISSUE THREAD

**Issue by huicewang** [danswer-ai/danswer#1030]
How to access DAnswer through an API interface?

**Comment by cypris75** [comment]
Would love to see this as well to integrate this into existing websites / knowledge bases. 

Similar to what Mintlify offers.

https://mintlify.com/docs/api-playground/openapi/setup

https://mintlify.com/blog/chat

**Comment by nigelsim** [comment]
I'd also love to use DAnswer as the single source of indexed data, so I can build other LLM tools on top of it. 

e.g., an API to search for and retrieve the text from documents matching a query (like happens on the RHS when it retrieves relevant documents). This way I can use the retrieved text in another LLM app.

Then, normal question/chat against any configured persona.

This would make the security around these integrated datasets a lot easier to manage, rather than having multiple disparate apps all separately indexing and storing the data.

**Comment by cheunj3** [comment]
+1

**Comment by Poltuu** [comment]
Any opinion as to the possibility of such feature ? It would be a real game changer for us

**Comment by yuhongsun96** [comment]
Hey folks! The API Key feature is now in MIT! Huzzah!

**Comment by elvis-cai** [comment]
super, can't wait to test it

**Comment by icebearlabs** [comment]
@yuhongsun96 Maybe I'm dumb or need more coffee, but I don't understand where this brings us now? Can we use the API now? Is it just the endpoints you can also find under https://docs.onyx.app/apis/answer_with_quote ?

**Comment by yuhongsun96** [comment]
Hi, some endpoints have been reworked slightly, the docs haven't gotten updated yet unfortunately. We will take a pass at it soon!

**Comment by icebearlabs** [comment]
@yuhongsun96 that's fine but is there a code snippet somewhere, how to access Danswer communtiy version through API? Should I see a API Keys Tab in the newest community version when installing that?

**Comment by yuhongsun96** [comment]
<img width="1491" alt="image" src="https://github.com/user-attachments/assets/9a805114-448e-4ec6-b49c-4a134ae2215d" />
Yup, it looks like this

**Comment by twiecki** [comment]
I have created an API key but I'm not able to connect to port 8080 on the community cloud or my own locally running onyx server (running on docker compose).

**Comment by twiecki** [comment]
## Onyx API Integration Guide

  After investigating the Onyx API, we've successfully implemented the integration. Here's a summary of how to interact with the API for others who might need it.

  ### Authentication

  - Use Bearer token authentication with your API key
  - Header format: `Authorization: Bearer on_your_api_key_here`
  - Alternative header also supported: `X-Onyx-Authorization: Bearer on_your_api_key_here`

  ### Two-Step Process

  The API works in two steps:

  1. **Create a chat session**
     ```python
     # Step 1: Create a chat session
     session_endpoint = "https://{your-onyx-instance}/api/chat/create-chat-session"
     session_data = {
         "persona_id": 0,  # Use default persona
         "description": "Optional session description"
     }
     response = requests.post(session_endpoint, headers=headers, json=session_data)
     chat_session_id = response.json()["chat_session_id"]

  2. Send a message to get an answer
  # Step 2: Send a message
  message_endpoint = "https://{your-onyx-instance}/api/chat/send-message"
  message_data = {
      "message": "What is X?",
      "chat_session_id": chat_session_id,
      "parent_message_id": None,
      "file_descriptors": [],    # Required field
      "prompt_id": None,         # Required field
      "search_doc_ids": [],      # Required field
      "retrieval_options": {
          "run_search": "always",
          "real_time": True
      }
  }
  response = requests.post(message_endpoint, headers=headers, json=message_data)

  Handling Streaming Responses

  The response from the send-message endpoint is a streaming format with multiple JSON objects. Each line contains a separate JSON object that needs to be parsed individually:

  # Process streaming response
  content = response.text
  combined_answer = ""

  for line in content.splitlines():
      if not line.strip():
          continue

      try:
          chunk = json.loads(line)
          if "answer_piece" in chunk:
              combined_answer += chunk["answer_piece"]
      except json.JSONDecodeError:
          continue

  # Combined answer now contains the full response

  Key Findings

  1. The /api prefix is required for all API endpoints
  2. Several "required" fields need to be included even if empty
  3. Use persona_id=0 for default assistant
  4. Responses are streamed as multiple JSON objects, each on its own line
  5. The answer comes in pieces that need to be combined

  Hope this helps others integrating with the Onyx API!
