### ISSUE TITLE
Notion Connector - CONTINUE_ON_CONNECTOR_FAILURE support

### ISSUE THREAD

**Issue by yanaemon** [danswer-ai/danswer#1053]
Hello.

We are currently facing a problem where index always fails on certain documents and does not proceed, with the following error.
```
400 Client Error: Bad Request for url: https://api.notion.com/v1/blocks/1d0dc31e-cd1b-4c15-a717-5f14c0a9e537/children
```

Notion API does not seem to support retrieving AI blocks.
```
{"object":"error","status":400,"code":"validation_error","message":"Block type ai_block is not supported via the API for your bot type.","request_id":"8359030e-35cf-4395-a384-0a92c0c689a0"}
```

This will always result in an error and the index job will stop.

Reading the code, it seems that the environment variable `CONTINUE_ON_CONNECTOR_FAILURE` exists but is not used by the Notion Connector.

Is there any plan to support CONTINUE_ON_CONNECTOR_FAILURE in Notion Connector?
I can raise you a PR if there are no reason about using it.

Thanks.

**Comment by Weves** [comment]
Hey @yanaemon! Hmm, we could definitely support the `CONTINUE_ON_CONNECTOR_FAILURE` env variable but it might better to just handle this gracefully in the notion connector? 

If possible, would you have the bandwidth to put something like that in? E.g. add a check https://github.com/danswer-ai/danswer/blob/main/backend/danswer/connectors/notion/connector.py#L109 which handles this case and continues?

**Comment by yanaemon** [comment]
@Weves Thanks for confirming!

I agree to that, it is better to handle it gracefully in the Notion Connector.
Notion API is a GET API and returns 400 instead of `405 Method Not Allowed` or `501 Not Implemented`.
https://developers.notion.com/reference/status-codes#error-codes
and It would not be scalable to hard code a specific message. 🤔 

So, How about just handling (log warn and continue!) all `status: 400 code: validation_error` error from GET API response?

**Comment by eugene-yaroslavtsev** [comment]
@Weves - I just sent a PR to handle this. Sorry, didn't add any tests - just went off of Notion API spec + [Airbyte's fix for same issue](https://github.com/airbytehq/airbyte/pull/25709/files#diff-c9b27094ad0140b4f070897905b197dbe40328e56792e12b8e02893e622e5890R259)

Side note: @yanaemon and I work together - he got our Danswer instance up and running during a hackathon we did a few weeks ago. Thanks for building a great product. If you or Yuhong (sorry, stalked you guys on bookface 🤫) are ever in Tokyo,  come visit our office in Ginza - we've got a bunch of open desks you can use and we'll take you to a great ramen spot nearby <3 Just ping me on FB or Linkedin

**Comment by Weves** [comment]
@eugene-yaroslavtsev wow, that is an amazing offer 🙇 

We will definitely keep that in mind if (when) we do make the trek over to Tokyo 😉
