### ISSUE TITLE
Quickstart tutorial not working with an Azure OpenAI endpoint

### ISSUE THREAD

**Issue by swisman** [danswer-ai/danswer#1057]
Great project first of all! Unfortunately, I'm facing issues following the [quickstart tutorial ](https://docs.danswer.dev/quickstart ) to use an Azure OpenAI endpoint.

What I did is the following:

1. Cloned repo 
2. Created an .env file and specified all env vars as shown in the [docs](https://docs.danswer.dev/gen_ai_configs/azure)
3. Run docker compose command to pull images from DockerHub:
`docker compose -f docker-compose.dev.yml -p danswer-stack up -d` 
Note that --pull flag is not supported for my setup, I'm running on docker compose v2.3.3 (see below).
4. Go to http://localhost:3000/ and try to chat.

Looking into the api server (danswer-stack-api_server-1) logs I can see that validation of the api key fails
````
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     172.19.0.7:56324 - "GET /health HTTP/1.1" 200 OK
INFO:     172.19.0.6:53054 - "GET /auth/type HTTP/1.1" 200 OK
INFO:     172.19.0.6:53056 - "GET /manage/me HTTP/1.1" 403 Forbidden
INFO:     172.19.0.6:53054 - "GET /auth/type HTTP/1.1" 200 OK
INFO:     172.19.0.6:53056 - "GET /manage/me HTTP/1.1" 403 Forbidden
INFO:     172.19.0.6:53072 - "GET /query/valid-tags HTTP/1.1" 200 OK
INFO:     172.19.0.6:53066 - "GET /manage/connector HTTP/1.1" 200 OK
INFO:     172.19.0.6:53068 - "GET /manage/document-set HTTP/1.1" 200 OK
INFO:     172.19.0.6:53070 - "GET /persona HTTP/1.1" 200 OK
INFO:     172.19.0.7:56398 - "GET /health HTTP/1.1" 200 OK
INFO:     172.19.0.6:53054 - "GET /auth/type HTTP/1.1" 200 OK
INFO:     172.19.0.6:53056 - "GET /manage/me HTTP/1.1" 403 Forbidden
INFO:     172.19.0.6:53068 - "GET /manage/document-set HTTP/1.1" 200 OK
INFO:     172.19.0.6:53072 - "GET /query/valid-tags HTTP/1.1" 200 OK
INFO:     172.19.0.6:53066 - "GET /manage/connector HTTP/1.1" 200 OK
INFO:     172.19.0.6:53070 - "GET /persona HTTP/1.1" 200 OK
02/08/2024 01:24:03 PM             utils.py 188 : GenAI API key failed for the following reason: Connection error.
02/08/2024 01:24:05 PM             utils.py 188 : GenAI API key failed for the following reason: Connection error.

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.


Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

INFO:     172.19.0.7:56400 - "HEAD /manage/admin/genai-api-key/validate HTTP/1.1" 400 Bad Request
INFO:     172.19.0.7:56416 - "GET /health HTTP/1.1" 200 OK
INFO:     172.19.0.6:53146 - "GET /manage/me HTTP/1.1" 403 Forbidden
INFO:     172.19.0.6:53148 - "GET /auth/type HTTP/1.1" 200 OK
INFO:     172.19.0.7:56544 - "GET /health HTTP/1.1" 200 OK
````

I digged a bit into the code and I think that test_llm (from danswer.llm.utils) fails. However, the key and all other llm endpoint settings are correct* and everything seems to be correclty set as env vars in the running container!

*The settings are working locally - I've copied the relevant code snippet - as well as when I'm starting the api server container using docker and connecting to it (using `docker run -it danswer/danswer-backend:latest /bin/bash`). On the other side they're not working when I connect to the running container after having started it with docker compose. Fortunately, I get a a better error message in this case

```
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpcore/backends/sync.py", line 94, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

Apparently, DNS resolution for my Azure OpenAI endpoint is not working. But the OpenAI endpoint can be reached: Inserting an OpenAI key in the popup everything works like a charm. I'm quite confused now. 

**Has anyone experience the same or did anyone get it up and running with Azure OpenAI GenAI model? Appreciate your help!**

Note: I'm using wsl (v2) on Windows 11 with Ubuntu 20.04.4 LTS. 

> Client:
>  Context:    default
>  Debug Mode: false
>  Plugins:
>   compose: Docker Compose (Docker Inc., v2.3.3)
> Server:
>  Containers: 8
>   Running: 6
>   Paused: 0
>   Stopped: 2
>  Images: 40
>  Server Version: 20.10.12
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Native Overlay Diff: true
>   userxattr: false
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Cgroup Version: 1
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: inactive
>  Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version:
>  runc version:
>  init version:
>  Security Options:
>   seccomp
>    Profile: default
>  Kernel Version: 5.10.102.1-microsoft-standard-WSL2
>  Operating System: Ubuntu 20.04.4 LTS
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 12
>  Total Memory: 15.53GiB
>  Name: xxx
>  ID: VZSW:XDMC:QBIA:WRFU:RBER:ODVF:NS3I:QV7I:7EXV:MM4Z:AYLS:63PT
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: false
>  Registry: https://index.docker.io/v1/
>  Labels:
>  Experimental: false
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false
> 
> WARNING: No blkio throttle.read_bps_device support
> WARNING: No blkio throttle.write_bps_device support
> WARNING: No blkio throttle.read_iops_device support
> WARNING: No blkio throttle.write_iops_device support

**Comment by swisman** [comment]
Solved it. Sharing my solution if someone faces the same issue.
I need to add the correct nameserver for me to be used in danswer-backend container. The server is defined in /etc/resolv.conf 
![image](https://github.com/danswer-ai/danswer/assets/78741412/5733094e-c4ad-4d18-b976-44217ebd936e)

To find out which is the right one for me I did run the following:

1. docker run -it danswer/danswer-backend:latest /bin/bash
2. apt update
3. apt install nano
4. nano /etc/resolv.conf

Please note that 

- don't remove the other nameserver listed /etc/resolv.conf 
- order of the nameserver listed doesn’t matter, both works fine for me
- for me the nameserver is not static per device! Mine changes frequently (e.g. over night)!

**Comment by efthnakas** [comment]
Hello, 

I am facing exactly the same issue. Following your solution I have located the correct nameserver for me in the resolv.config file but after that I am not sure I understand. Can you please describe in more detail what are the steps after that?  Where exactly I need to add the correct nameserver?

Thanks

**Comment by swisman** [comment]
> Hello,
> 
> I am facing exactly the same issue. Following your solution I have located the correct nameserver for me in the resolv.config file but after that I am not sure I understand. Can you please describe in more detail what are the steps after that? Where exactly I need to add the correct nameserver?
> 
> Thanks

as far as I remember (it has been a while, sorry), the steps 1-4 above just described how to find the currently correct nameserver for you. Once you have retrieved this information, you have to use it and alter the running instance of danswer. That is, after having started danswer using docker compose you need 

1. to connect to the danswer-backend container that is then running (using docker exec -it <container_name_or_id> /bin/bash afaik)
2. add the nameserver to the resolv.conf file that you found as shown in the screenshot. For this you simply follow steps 2-4 in my initial description. 
 
After having changed the resolv.conf danswer worked for me with an AzureOpenAI backend. 
To test right away if the Azure endpoint can be reached, you may also open a python console in the danswer-backend container that you are connected to. Then copy (after replacing the placeholders with your specific infos) the code below to the python console and run it. This should you give something like

![image](https://github.com/user-attachments/assets/2d611b91-bbce-472e-94cc-f490bf89a4eb)

```
from langchain.chat_models import ChatLiteLLM
import litellm

llm_api = {'GEN_AI_MODEL_PROVIDER': 'azure',
 'GEN_AI_MODEL_VERSION': '<your model>',
 'GEN_AI_API_ENDPOINT': '<your Azure endpoint>.openai.azure.com/',
 'GEN_AI_API_VERSION': '<your API version'}

api_key = '<your key>'

litellm.api_key = api_key
litellm.api_version = llm_api["GEN_AI_API_VERSION"]

model = f'{llm_api["GEN_AI_MODEL_PROVIDER"]}/{llm_api["GEN_AI_MODEL_VERSION"]}'
api_base = llm_api["GEN_AI_API_ENDPOINT"]

llm = ChatLiteLLM(
    model=model,
    api_base=api_base,
    custom_llm_provider=None,
    max_tokens=1024,
    temperature=1,
    verbose=True, #should_be_verbose(),
    max_retries=0,  # retries are handled outside of langchain
)

llm.invoke("Do not respond")
```
