### ISSUE TITLE
images can't be displayed properly

### ISSUE THREAD

**Issue by mercurialgh** [danswer-ai/danswer#118]

**Comment by mercurialgh** [comment]
https://github.com/shibing624/nlp-tutorial/blob/main/01_word_embedding/01_%E6%96%87%E6%9C%AC%E8%A1%A8%E7%A4%BA.ipynb

**Comment by Weves** [comment]
Did you mean to open this issue against a different repo (`shibing624/nlp-tutorial`)? 😅

**Comment by yuhongsun96** [comment]
Closing, no response from reporter, probably wrong repo
