### ISSUE TITLE
Not generating responses after multiple rounds of talks in a same chat.

### ISSUE THREAD

**Issue by NeverOccurs** [danswer-ai/danswer#1271]
Is it a because of context limit? Seems the issue is only with Qwen models.

**Comment by adlotsof** [comment]
how did you solve this?

**Comment by NeverOccurs** [comment]
> how did you solve this?

just switched to another model.

**Comment by adlotsof** [comment]
so i got a hacky fix, in case someone else finds this:
1. calculate the difference in token count between the models tokenizer and tiktoken encoding, should be about 0.7-0.8 less tokens counted by tiktoken compared to openchat. 
2. use [this](https://litellm.vercel.app/docs/completion/token_usage#8-register_model) to register openchat - max_tokens is the most important setting. Use your llm backend context_size or max_input_tokens setting and multiply by 0.7 - thats the max_tokens for the register model. you can do the call to register_model in the place of the code your litellm model is initialized
3. danswer should now count a similar amount of tokens as the openchat tokenizer.
