### ISSUE TITLE
Notion polling is unnecessarily slow

### ISSUE THREAD

**Issue by spagnoloe-capchase** [danswer-ai/danswer#1325]
We have noticed that the Notion connector is extremely slow, even after the first successful sync.

The reason is that, despite having few new pages updated since the last sync, it reads all the documents from history every time. In our case these are roughly 54k docs, so it takes a very long time.

Looking at the code we have noticed that, despite fetching the pages order by `last_edited_time`, if at some point there [are no new documents updated](https://github.com/danswer-ai/danswer/blob/b59912884bed7a32a0858d2e634d5402647c5ea6/backend/danswer/connectors/notion/connector.py#L434), it still keeps running the polling of more pages (see [here](https://github.com/danswer-ai/danswer/blob/b59912884bed7a32a0858d2e634d5402647c5ea6/backend/danswer/connectors/notion/connector.py#L436)).

Hence, we should only be fetching new pages if there have been pages extracted from the last search API call

**Comment by spagnoloe-capchase** [comment]
This is issue is solved with this [PR](https://github.com/danswer-ai/danswer/pull/1323).

**Comment by Weves** [comment]
Resolved! Thanks again for the fix.
