### ISSUE TITLE
Setup GitHub Actions to build Docker images

### ISSUE THREAD

**Issue by rursache** [danswer-ai/danswer#135]
Please setup GitHub Actions to build docker images so we don't have to build them for each update. 
Thanks

EDIT: Would love a AIO linuxserver.io-like image as well.

**Comment by firestrife23** [comment]
That would be nice!

**Comment by yuhongsun96** [comment]
First part of adding github actions to build images, push to hub, and tag is done. Images found at https://hub.docker.com/repositories/danswer

Will keep this issue open while we do the All-in-one image.

**Comment by yuhongsun96** [comment]
I think most of the value here was achieved by the Github Actions which pushes the docker images to Hub. Therefore, deprioritizing the second part of creating an all-in-one image, but if someone else wants to take it up, it would definitely be good to have.

Will get to this eventually though if nobody else takes it up, just there are higher priority items.
