### ISSUE TITLE
Gmail support

### ISSUE THREAD

**Issue by cagnulein** [danswer-ai/danswer#137]
I'm doing a lot of tech support by email and I have a lot of recurrent questions. Is is possible to integrate gmail as well?
Thanks!

**Comment by itayB** [comment]
Here is a PR for that: https://github.com/danswer-ai/danswer/pull/946

**Comment by itayB** [comment]
@yuhongsun96 I think you can close this issue, right?

**Comment by yuhongsun96** [comment]
Ah ya, haven't been doing GitHub Issues cleanup very much. Thanks for pointing this out, closing this one and thanks for the contrib!
