### ISSUE TITLE
Zulip connector

### ISSUE THREAD

**Issue by elo-siema** [danswer-ai/danswer#138]
I could really use a Zulip connector for this. I wonder if anyone else would like one?

**Comment by elo-siema** [comment]
@yuhongsun96 Claiming this issue, I'd like to work on it

**Comment by yuhongsun96** [comment]
Closed with above PR

**Comment by yuhongsun96** [comment]
Thanks @elo-siema for the contribution

**Comment by yuhongsun96** [comment]
Added the docs: https://docs.danswer.dev/connectors/zulip
@elo-siema, let me know if they're correct, I'm not as familiar with Zulip
