### ISSUE TITLE
context length Ollama

### ISSUE THREAD

**Issue by Smensink** [danswer-ai/danswer#1467]
i'm having trouble figuring out how to increase the context length when using ollama as a llm source, it's stuck on the default 2048

**Comment by raymond-infinitecode** [comment]
this has to be configure from the ollama 
ollama show model:latest --modelfile

Copy the modelfile on console and save it to modelname.model
Edit the modelname.model file to change the context length
For example e.g. (Model file content)

# Modelfile generated by "ollama show"
# To build a new Modelfile based on this one, replace the FROM line with:
# FROM llama3:8b-instruct-q4_K_M

FROM /home/xuser/.ollama/models/blobs/sha256:60af83b47d53e839830a77eb7cf8b7d473a8b4f778aca21dc73b337a304c4b54
TEMPLATE """{{ if .System }}<|start_header_id|>system<|end_header_id|>

{{ .System }}<|eot_id|>{{ end }}{{ if .Prompt }}<|start_header_id|>user<|end_header_id|>

{{ .Prompt }}<|eot_id|>{{ end }}<|start_header_id|>assistant<|end_header_id|>

{{ .Response }}<|eot_id|>"""
PARAMETER num_thread 16
**PARAMETER num_ctx 8192**
PARAMETER num_keep 24
PARAMETER stop "<|start_header_id|>"
PARAMETER stop "<|end_header_id|>"
PARAMETER stop "<|eot_id|>"

Change the parameter num_ctx to the value you want and save it

After that

ollama create newmodel:latest -f modelname.model
ollama run newmodel:latest

**Comment by Smensink** [comment]
you are an absolute lifesaver, i couldn't find this information anywhere for some reason
