### ISSUE TITLE
Latest images throwing exceptions

### ISSUE THREAD

**Issue by dstrzelec** [danswer-ai/danswer#1482]
Slack thread:  https://danswer.slack.com/archives/C056265VB1N/p1715895013347759

I upgraded from v.0.3.72 to latest on Thursday May 16, (git pull, and docker force-recreate), and now the web frontend is throwing an HTTP 400 exception, and the API server is throwing errors referring to no default LLM set in the DB. Other people seem to be experiencing this as well (see Slack thread).

Browser message:
`Application error: a client-side exception has occurred (see the browser console for more information).`

Browser console messages:
```
POST https://danswer.corpaxe.com/api/admin/llm/test/default 400 (Bad Request)

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bname%2C%20description%2C%20is_required%2C%20is_secret%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at nT (fd9d1056-3b3f42a69822c31e.js:1:30255)
    at s (fd9d1056-3b3f42a69822c31e.js:1:35762)
    at u (fd9d1056-3b3f42a69822c31e.js:1:35940)
    at lT (fd9d1056-3b3f42a69822c31e.js:1:57186)
    at iB (fd9d1056-3b3f42a69822c31e.js:1:120252)
    at o4 (fd9d1056-3b3f42a69822c31e.js:1:94633)
    at fd9d1056-3b3f42a69822c31e.js:1:94455
    at o3 (fd9d1056-3b3f42a69822c31e.js:1:94462)
    at oj (fd9d1056-3b3f42a69822c31e.js:1:90814)
    at MessagePort.M (8069-ca5b18aebe4acfc9.js:1:98699)
```

API Server errors:
```
05/16/2024 10:02:30 PM               api.py  91 : Failed to fetch default LLM Provider
Traceback (most recent call last):
  File "/app/danswer/server/manage/llm/api.py", line 88, in test_default_provider
    llm = get_default_llm()
          ^^^^^^^^^^^^^^^^^
  File "/app/danswer/llm/factory.py", line 49, in get_default_llm
    raise ValueError("No default LLM provider found")
ValueError: No default LLM provider found
```

I have tried rolling back to the v0.3.73 images of backend and model server but get the same errors. I suspect this is the release where the issue was introduced. I then tried rolling back to v0.3.72, but get the below error messages in the API Server, and the API Server container won't start up.

```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
FAILED: Can't locate revision identified by '3879338f8ba1'
ERROR [alembic.util.messaging] Can't locate revision identified by '3879338f8ba1'
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
```

**Comment by Weves** [comment]
Hey @dstrzelec we were running into some issues with the Web server build which caused a mismatch between the backend/web containers. This is likely the root cause of the issue. 

Can you try pulling the latest image, and then going to the `LLM` page to setup a new LLM provider?

**Comment by dstrzelec** [comment]
That worked @Weves. Thanks for resolving the bug.
