### ISSUE TITLE
Chat crashes when encountered unknown code syntax 

### ISSUE THREAD

**Issue by david-prv** [danswer-ai/danswer#1518]
When I try to get some Apache2 configuration code snippet, the chat crashes with `Application error: a client-side exception has occurred (see the browser console for more information)`. I suppose it's because the Danswer tries to highlight the source code but notices that it does not know `apache`?

![image](https://github.com/danswer-ai/danswer/assets/66866223/80cc3f2f-33a2-4a9b-935d-568f6d303a89)

**Comment by david-prv** [comment]
Well, unfortunately, I can't even open the chat again nor can I delete it anymore xD Everytime I enter the chat, it instantly crashes again. That's a little bit pain right now

**Comment by Chillwind132** [comment]
+1

**Comment by Weves** [comment]
Hey @david-prv and @Chillwind132, just put in a fix here: https://github.com/danswer-ai/danswer/pull/1525! 

Sorry about the inconvenience, and let me know if you're still running into issues after pulling in the latest and re-building.
