### ISSUE TITLE
Not able to install using docker compose

### ISSUE THREAD

**Issue by rudraksh97** [danswer-ai/danswer#152]
Stack Trace:

1223.9 Collecting nvidia-nccl-cu11==2.14.3 (from torch>=1.6.0->sentence-transformers==2.2.2->-r /tmp/requirements.txt (line 32))
1223.9   Downloading nvidia_nccl_cu11-2.14.3-py3-none-manylinux1_x86_64.whl (177.1 MB)
1249.8      ━━━━━━━━━━━━━╸                           60.3/177.1 MB 4.8 MB/s eta 0:00:25
1249.8 ERROR: Exception:
1249.8 Traceback (most recent call last):
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
1249.8     yield
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
1249.8     data = self._fp_read(amt) if not fp_closed else b""
1249.8            ^^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
1249.8     return self._fp.read(amt) if amt is not None else self._fp.read()
1249.8            ^^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/http/client.py", line 466, in read
1249.8     s = self.fp.read(amt)
1249.8         ^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/socket.py", line 706, in readinto
1249.8     return self._sock.recv_into(b)
1249.8            ^^^^^^^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/ssl.py", line 1278, in recv_into
1249.8     return self.read(nbytes, buffer)
1249.8            ^^^^^^^^^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/ssl.py", line 1134, in read
1249.8     return self._sslobj.read(len, buffer)
1249.8            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1249.8 TimeoutError: The read operation timed out
1249.8
1249.8 During handling of the above exception, another exception occurred:
1249.8
1249.8 Traceback (most recent call last):
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
1249.8     status = run_func(*args)
1249.8              ^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
1249.8     return func(self, options, args)
1249.8            ^^^^^^^^^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
1249.8     requirement_set = resolver.resolve(
1249.8                       ^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
1249.8     result = self._result = resolver.resolve(
1249.8                             ^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
1249.8     state = resolution.resolve(requirements, max_rounds=max_rounds)
1249.8             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in resolve
1249.8     failure_causes = self._attempt_to_pin_criterion(name)
1249.8                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 239, in _attempt_to_pin_criterion
1249.8     criteria = self._get_updated_criteria(candidate)
1249.8                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 230, in _get_updated_criteria
1249.8     self._add_to_criteria(criteria, requirement, parent=candidate)
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
1249.8     if not criterion.candidates:
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
1249.8     return bool(self._sequence)
1249.8            ^^^^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
1249.8     return any(self)
1249.8            ^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
1249.8     return (c for c in iterator if id(c) not in self._incompatible_ids)
1249.8            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
1249.8     candidate = func()
1249.8                 ^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
1249.8     self._link_candidate_cache[link] = LinkCandidate(
1249.8                                        ^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
1249.8     super().__init__(
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
1249.8     self.dist = self._prepare()
1249.8                 ^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
1249.8     dist = self._prepare_distribution()
1249.8            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
1249.8     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
1249.8            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
1249.8     return self._prepare_linked_requirement(req, parallel_builds)
1249.8            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 587, in _prepare_linked_requirement
1249.8     local_file = unpack_url(
1249.8                  ^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
1249.8     file = get_http_url(
1249.8            ^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
1249.8     from_path, content_type = download(link, temp_dir.path)
1249.8                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/network/download.py", line 147, in __call__
1249.8     for chunk in chunks:
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
1249.8     for chunk in iterable:
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
1249.8     for chunk in response.raw.stream(
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
1249.8     data = self.read(amt=amt, decode_content=decode_content)
1249.8            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
1249.8     with self._error_catcher():
1249.8   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
1249.8     self.gen.throw(typ, value, traceback)
1249.8   File "/usr/local/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
1249.8     raise ReadTimeoutError(self._pool, None, "Read timed out.")
1249.8 pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
------
failed to solve: process "/bin/sh -c pip install --no-cache-dir --upgrade -r /tmp/requirements.txt" did not complete successfully: exit code: 2

**Comment by yuhongsun96** [comment]
Could you try with the updated instructions which pulls from hub instead of building and installing reqs
https://docs.danswer.dev/quickstart

Let me know if this works for you

**Comment by rudraksh97** [comment]
It has been resolved. Docker compose failed several times, but in the end, the deployment got completed. Just ran the command several times, it picked the remaining installation every time and kept moving ahead a bit.
