### ISSUE TITLE
GitLab Connector

### ISSUE THREAD

**Issue by Nezteb** [danswer-ai/danswer#154]
Similar to https://docs.danswer.dev/connectors/github

**Comment by Rutik7066** [comment]
Hey @yuhongsun96 may i get assigned so that other folks won't be confused

**Comment by Rutik7066** [comment]
> Hey @yuhongsun96 may i get assigned so that other folks won't be confused

😑

**Comment by yuhongsun96** [comment]
Sounds good, you got it!

**Comment by Min2who** [comment]
@yuhongsun96 i have started working on that ?

**Comment by Rutik7066** [comment]
Thanks @yuhongsun96

**Comment by Rutik7066** [comment]
Hi @pbkompasz I am working on it could you please find some other?

**Comment by pbkompasz** [comment]
Hi @yuhongsun96,
Noting that @Rutik7066's progress has been slow this past week, I'd like to step in. I've already begun backend work and can promptly submit a PR for the implementation, along with another for the docs. Can I be assigned to this?

Thanks

**Comment by Rutik7066** [comment]
> Hi @yuhongsun96,
> Noting that @Rutik7066's progress has been slow this past week, I'd like to step in. I've already begun backend work and can promptly submit a PR for the implementation, along with another for the docs. Can I be assigned to this?
> 
> Thanks

Don't you see that this issue has been assigned to me why don't you look for other issues i have also completed backend and now i am testing it. Look for other issues. I request you @yuhongsun96 please assign him other issues he is really willing to contribute on the project. Bounty doesn't matter for him. I guess

**Comment by yuhongsun96** [comment]
Hi @pbkompasz, since @Rutik7066 has the issue assigned to him and hasn't shown any signs that he would not be able to complete it, the issue will remain with him unless circumstances change. I appreciate your eagerness to contribute, there will be other connector bounties in the future!

**Comment by pbkompasz** [comment]
@yuhongsun96 Is there a time limit for completing a bounty? I assumed someone cannot lock in a bounty for a longer period without showing any progress.

**Comment by yuhongsun96** [comment]
Paid out a partial of 100$, reducing end amount to 150$ to keep the total bounty consistent
