### ISSUE TITLE
I want to delete some files in a connector

### ISSUE THREAD

**Issue by saber72237** [danswer-ai/danswer#1565]
I want to delete some files in a file connector, not all of them, and I don't want to delete the connector itself. What should I do?

**Comment by 415matt** [comment]
In the explorer tool on the admin panel search for the document you want to delete and set it's visibility to hidden

**Comment by 415matt** [comment]
<img width="1452" alt="image" src="https://github.com/danswer-ai/danswer/assets/22831508/73b3fa97-5ed7-4de7-913e-0117336dd829">
*example*
