### ISSUE TITLE
Developer Guide for contributing connectors

### ISSUE THREAD

**Issue by snth** [danswer-ai/danswer#158]
Hi,

Perhaps you could put together a Developer Guide for contributing connectors and add it to https://docs.danswer.dev/connectors/overview?

I just opened a couple of connector issues myself and I see there were a couple of other ones before me. If it's not too difficult this is where the community and open source could really shine.

I think this approach has worked really well for projects like [Ruff](https://github.com/astral-sh/ruff) for example.

All the best!

**Comment by yuhongsun96** [comment]
Working on a CONTRIBUTING.md today, will also release the docs as opensource so contributors can also explain the setup for the connector.

**Comment by yuhongsun96** [comment]
CONTRIBUTING.md and opensourcing docs are done.

Marking this as closed.

If anyone feels that the process is still confusing or would like more details on how to contribute connectors, please comment below, happy to provide more if needed.

**Comment by yuhongsun96** [comment]
https://github.com/danswer-ai/danswer/blob/main/backend/danswer/connectors/README.md

Additionally added README in connectors directory for how to contribute

and mentioned in https://docs.danswer.dev/connectors/overview as requested
