### ISSUE TITLE
PDF file upload not correctly parsed

### ISSUE THREAD

**Issue by plopezamaya** [danswer-ai/danswer#1624]
While using the `v3.0.79` It seems that some pdfs are not currently parsed well when using `from pypdf import PdfReader` in `backend/danswer/file_processing/extract_file_text.py`.

The result is that the llm answers that it cannot retrieve any information from the given document. Should a OCR reader or other framework be used for this ?

**Comment by arrfandannge** [comment]
You might need to use OCR to extract text, If the PDFs contain scanned images or are image-based.
pytesseract along-with an image processing library like Pillow should work to extract text from images within PDFs.

**Comment by plopezamaya** [comment]
@arrfandannge  Meaning that what is implemented today in danswer should be replaced by an OCR or Pillow ?

**Comment by arrfandannge** [comment]
> @arrfandannge Meaning that what is implemented today in danswer should be replaced by an OCR or Pillow ?

I suggest keeping the current implementation intact but adding code that uses OCR as a fallback method when pypdf doesn't help. This will keep the solution robust and ensure efficiency because extraction with pypdf is generally faster than OCR.
