### ISSUE TITLE
add Cloudflare web connector authentication

### ISSUE THREAD

**Issue by hagen-danswer** [danswer-ai/danswer#1641]
right now, the web connector cannot index websites protected by Cloudflare authentication.

Ideally, the web connector would include a way to input credentials to allow it to index pages hidden behind that authentication.

**Comment by productnerdio** [comment]
Thanks @hagen-danswer 

Cloudflare requires the following to be passed as headers, in the way we are accessing protected content:

CF-Access-Client-Id: <key>
CF-Access-Client-Secret: <secret>
