### ISSUE TITLE
React Hot Reload

### ISSUE THREAD

**Issue by lemesh2424** [danswer-ai/danswer#1657]
Is it possible to configure hot reload for react using docker?
If want to make some adjustments for myself, is it possible without rebuilding docker container?

**Comment by iamitpal** [comment]
<img width="551" alt="Screenshot 2024-06-26 at 9 49 57 AM" src="https://github.com/danswer-ai/danswer/assets/109168129/fa6e8f17-fdc6-4043-9945-c67c7610b410">


docker compose up --watch

adding this to your docker file will enable hotreload

**Comment by lemesh2424** [comment]
Thank you!
