### ISSUE TITLE
[FEATURE REQUEST]Document ingestion/chunking settings

### ISSUE THREAD

**Issue by dukemagus** [danswer-ai/danswer#166]
Please add an "advanced settings" section on the document upload/ingestion page exposing the chunking options before tokenizing.

More important among them

Chunk size (in characters) New models with better indexing capabilities are appearing and it's very possible we'll get some upgrade on ada 002 witha higher token limit.

Chunk overlap: Having a small overlapping text between the end of one chunk and the start of the other improves vector DB search results.

Metadata edit: columns per chunk: chunk number, document page, document name and, if possible, an optional field to add a some additional info (alternative document address, for example).

**Comment by wwzeng1** [comment]
Hi! I’m one of the founders of Sweep, a github app that solves issues(like adding small features) by writing pull requests. 
This looks like a good issue for Sweep https://github.com/sweepai/sweep to try.
We have onboarding [instructions here](https://github.com/sweepai/sweep/blob/main/README.md#-getting-started), I’m also happy to help you onboard directly :)

**Comment by dukemagus** [comment]
That's interesting and the logic is doable with AI pair programming, but
the UI part needs someone that knows how to make things fit in the mold.
I'm not sure AI can alter a page schema by itself safely

Em qua., 12 de jul. de 2023 17:44, wwzeng1 ***@***.***>
escreveu:

**Comment by yuhongsun96** [comment]
https://github.com/danswer-ai/danswer/blob/main/backend/danswer/configs/app_configs.py#L106

You can change it here. The reason we didn't build a UI for it is because it adds to the complexity for the user/admin. It also requires an understanding of the model context window among other things so it's easy for someone to make the search worse or more expensive unintentionally

Does this do what you're thinking of?

**Comment by dukemagus** [comment]
Yeah, there are the values I mentioned.

Thanks

Em qua., 12 de jul. de 2023 22:14, Yuhong Sun ***@***.***>
escreveu:

**Comment by rkuo-danswer** [comment]
It looks like this issue was resolved overall via e-mail thread, so closing the issue here.
