### ISSUE TITLE
Assistants Don't Show Up

### ISSUE THREAD

**Issue by IAmStoxe** [danswer-ai/danswer#1660]
When I make a new assistant, they are not currently showing in the selectable menu.

I have validated that the assistant is "Visible" but doesn't appear where you'd expect.

![image](https://github.com/danswer-ai/danswer/assets/16467875/b1b734fb-4b12-4f3c-aeef-02ffe1216bd3)
![image](https://github.com/danswer-ai/danswer/assets/16467875/6d3aad46-e649-42ea-9583-a1264411366b)

![image](https://github.com/danswer-ai/danswer/assets/16467875/56a5d84c-0a93-42e5-9800-01ee5a520937)

**Comment by IMTanuki** [comment]
In a local windows implementation, my custom assistant appears in the drop-down picklist. But even though I moved it to the top position in the assistants list and selected it for a chat, danswer uses the default assistant for all responses.
