### ISSUE TITLE
Add mistral integration (european LLM)

### ISSUE THREAD

**Issue by woutersf** [danswer-ai/danswer#1662]
### MISTRAL AI?
Add mistral integration (european LLM)
Mistral is a european LLM provider,  a european GPT alternative. 

### Why Mistral?
Mistral loves 🇪🇺 europe and Europe loves Mistral. 
Mistral's french is much better than US competitors. 

### Python code
The API docs: [https://docs.mistral.ai/api/](https://docs.mistral.ai/api/)
We could use both the **embedding** as the **chat completion** API endpoints. 

There's already a python client available: 
[https://docs.mistral.ai/getting-started/clients/](https://docs.mistral.ai/getting-started/clients/)

### Reference
Frederik Wouters thinks the Mistral LLM dutch and french is substantially better and (feels more personal) than for example GPT 4. 
The reasoning capabilities are very strong.

**Comment by direction-technique-senova** [comment]
Please consider reopening this issue
