### ISSUE TITLE
Connectors are hanging with this new push

### ISSUE THREAD

**Issue by skprasadu** [danswer-ai/danswer#1679]
Team,

We have been using Danwer for a while and with this recent push, it seems, the connectors are hanging as shown below,

<img width="1265" alt="image" src="https://github.com/danswer-ai/danswer/assets/1975088/44caa74d-9553-4407-9df3-b718b1e5f772">

Also when I am trying to use ingestion API as per this [Link](https://docs.danswer.dev/backend_apis/ingestion), and when I have No Auth, it is giving me this error. Any help will be appreciated.

```
{
    "status_code": 422,
    "message": "[{'loc': ('header', 'authorization'), 'msg': 'field required', 'type': 'value_error.missing'}]",
    "data": null
}
```

**Comment by Arkantium** [comment]
Same for me

**Comment by skprasadu** [comment]
I was able to get past 1 thing, I am able to use ingestion API. when you start Danswer, you can do 

```
 docker logs -f <Container ID> 2>&1 | grep --line-buffered "Danswer API Key"
```

It will return the Bearer token, once we get that you can use that in the postman and we can ingest the data. And also able to search in the UI. This is cool.

I still have 2nd issue with "Scheduled" hung.

**Comment by skprasadu** [comment]
When ingesting data to Danswer using ingestion API, can we batch documents and insert? let me know if you support this feature.
