### ISSUE TITLE
Local Docker Image (Windows) - Option to Use a Local LLM (using LMStudio)

### ISSUE THREAD

**Issue by IMTanuki** [danswer-ai/danswer#1688]
New user here...

**Environment**
windows 11
danswer rev: 23.3.0
docker image

**Question**
Accessing a cloud-based LLM seems straightforward enough, but is it possible to access a local LLM via LM Studio? Goal here is to develop a portfolio of connectors, assistant prompts, etc.  without burning thru OpenAI (other) API credits. Indexing connectors (e.g. a single website) burned thru 300k tokens in a few minutes - for dev purposes, it would be much more cost-effective to use a local LLM - otherwise, I'm not sure I see the benefit of running danswer locally.

**Comment by mwieczorkiewicz** [comment]
Pretty much any `openai` API compliant service can be used with Danswer. AFAIK LM Studio exposes such API, so it should work out-of-the-box. 

You should use `openai` provider in your provider config. 

If you want to access the OpenAI API running locally (either via LM Studio or Ollama) you can just point it at your endpoint - if you're running `danswer` via `docker` just use `http://host.docker.internal:PORT/v1` (or `http://host.containers.internal:PORT/v1` for `podman`).

**Comment by radiogena** [comment]
@mwieczorkiewicz any chance to help how to connect external open api running at LM STUDIO? here is the pintscreens I use. do I need to write anything into .env file? I get no answers back from LM Studio. How to investigate? @IMTanuki have you find the solution?

![Screenshot 2025-01-10 at 09 58 19](https://github.com/user-attachments/assets/2fc3b7f8-040f-4417-8bc3-e418d4cd50e3)
![Screenshot 2025-01-10 at 09 58 51](https://github.com/user-attachments/assets/00baa153-a8fc-4e7b-87c7-da4f1405388c)
