### ISSUE TITLE
Feature Request: Delete Indexed Files

### ISSUE THREAD

**Issue by rehypothecation** [danswer-ai/danswer#174]
Issue:
There's currently no way to delete specific indexed files without removing the entire database. As it stands, if there's an error or if a file becomes irrelevant, the only solution is to clear the whole database, which isn't ideal.

Proposed Solution:
The ability to delete individual indexed files. This would mean adding a delete option in the interface that would remove the file from the system's database, Vector DB (Qdrant), and the search engine (Typesense).

**Comment by yuhongsun96** [comment]
Thanks for bringing creating a tracking issue. This has been on our backlog and fairly high in terms of priority for a while.
Probably will tackle this one after doing support for opensource models.

In the meantime, thanks for your patience! We've been getting a lot of request for new features, will get to this ASAP

**Comment by megamorf** [comment]
Maybe in addition to removing files from the index also look at moved/renamed resources. A user might rename a parent directory or move a big file where the indexed content itself doesn't change but just the metadata and it might be computationally expensive to reindex those resources. I have not yet looked at how the connectors and indexing handles this so ignore this message if that doesn't pose a problem :-)

**Comment by jabdoa2** [comment]
We got this issue too. Seems like we got some stuck documents from integrations we tested and even if it find the same document again in another integration it will not replace it. Not sure if that is because `semantic_id` is the same or something else (because `id` is certainly different).

**Comment by yuhongsun96** [comment]
Done! https://github.com/danswer-ai/danswer/pull/271

**Comment by yuhongsun96** [comment]
Will extend the feature in the near future with a "delete via search" approach, so that users can delete individual files that are surfaced via searching
