### ISSUE TITLE
facing issue while installing on Mac 

### ISSUE THREAD

**Issue by kshitiz305** [danswer-ai/danswer#1772]
` => ERROR [api_server  3/19] RUN apt-get update &&     apt-get install -y         cmake         curl         zip         ca-certificates       3.6s
------
 > [api_server  3/19] RUN apt-get update &&     apt-get install -y         cmake         curl         zip         ca-certificates         libgnutls30=3.7.9-2+deb12u2         libblkid1=2.38.1-5+deb12u1         libmount1=2.38.1-5+deb12u1         libsmartcols1=2.38.1-5+deb12u1         libuuid1=2.38.1-5+deb12u1         libxmlsec1-dev         pkg-config         gcc &&     rm -rf /var/lib/apt/lists/* &&     apt-get clean:
0.389 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
0.424 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
0.437 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
0.505 Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8788 kB]
1.342 Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [13.8 kB]
1.343 Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [165 kB]
2.281 Fetched 9221 kB in 2s (4802 kB/s)
2.281 Reading package lists...
2.823 Reading package lists...
3.366 Building dependency tree...
3.504 Reading state information...
3.510 Package libgnutls30 is not available, but is referred to by another package.
3.510 This may mean that the package is missing, has been obsoleted, or
3.510 is only available from another source
3.510 
3.512 E: Version '3.7.9-2+deb12u2' for 'libgnutls30' was not found
------
failed to solve: process "/bin/sh -c apt-get update &&     apt-get install -y         cmake         curl         zip         ca-certificates         libgnutls30=3.7.9-2+deb12u2         libblkid1=2.38.1-5+deb12u1         libmount1=2.38.1-5+deb12u1         libsmartcols1=2.38.1-5+deb12u1         libuuid1=2.38.1-5+deb12u1         libxmlsec1-dev         pkg-config         gcc &&     rm -rf /var/lib/apt/lists/* &&     apt-get clean" did not complete successfully: exit code: 100`

Issue while using `docker compose -f docker-compose.dev.yml -p danswer-stack up -d --build --force-recreate` command

**Comment by matthewjewell** [comment]
Commented in your PR but try pulling https://github.com/danswer-ai/danswer/commit/2035e9f39ccecedfba55bffc57c128f0806635e7
