### ISSUE TITLE
Login not possible after invitation created

### ISSUE THREAD

**Issue by martin-kuenzel** [danswer-ai/danswer#1776]
Hi,

Login with oauth as existing admin-user is not possible, when invitations have been sent.

The error message in the logs of api_server is:
`
        raise PermissionError("User not on allowed user whitelist")`

My guess is, that the problem might be at this point (due to missing entry in whitelist):

https://github.com/danswer-ai/danswer/blob/fa049f4f98c24d59cc36bcaa02139bec0f053e25/backend/danswer/auth/users.py#L173

**Comment by onimsha** [comment]
Yes. They changed the logic to check the email against the whitelist. The new logic is checking if the email is in the invitation list, which essentially blocking other users that are not in that list.
