### ISSUE TITLE
Dockerfile for model_server isn't copy config files

### ISSUE THREAD

**Issue by broken-wheel** [danswer-ai/danswer#1835]
`backend/model_server/constants.py` refers to `from danswer.search.enums import EmbedTextType` (https://github.com/danswer-ai/danswer/blob/main/backend/model_server/constants.py#L3), but the Dockerfile  (https://github.com/danswer-ai/danswer/blob/main/backend/Dockerfile.model_server) doesn't copy `danswer/search` to the image.

This patch may be sufficient:
```patch
diff --git a/backend/Dockerfile.model_server b/backend/Dockerfile.model_server
index 89f24e2a..ffaf5c20 100644
--- a/backend/Dockerfile.model_server
+++ b/backend/Dockerfile.model_server
@@ -41,6 +41,9 @@ COPY ./shared_configs /app/shared_configs
 # Model Server main code
 COPY ./model_server /app/model_server

+# danswer configs
+COPY ./danswer/search /app/danswer/search
+
 ENV PYTHONPATH /app

 CMD ["uvicorn", "model_server.main:app", "--host", "0.0.0.0", "--port", "9000"]
```

**Comment by broken-wheel** [comment]
I don't know why it was working before when I pulled the prebuilt docker images instead of building from source.

**Comment by Weves** [comment]
@broken-wheel thanks for the heads up! This has been fixed in https://github.com/danswer-ai/danswer/pull/1836.
