### ISSUE TITLE
Issue with Notion Connector: Tables and Databases Not Being Processed

### ISSUE THREAD

**Issue by MagnusHL** [danswer-ai/danswer#1848]
**Description:**
I am experiencing an issue with the Notion connector in Danswer. Specifically, tables and databases within Notion are not being evaluated or processed correctly. This is causing significant disruptions in our workflow as we rely heavily on these features for our data management.

**Steps to Reproduce:**
1. Connect Danswer to a Notion workspace.
2. Attempt to process or evaluate tables and databases within the Notion workspace.
3. Observe that the tables and databases are not being processed as expected.

**Expected Behavior:**
Tables and databases within Notion should be evaluated and processed correctly by the Danswer connector.

**Actual Behavior:**
Tables and databases are not being processed, leading to incomplete data evaluation.

**Comment by trial-danswer** [comment]
https://github.com/danswer-ai/danswer/pull/3274
