### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Farscaper** [danswer-ai/danswer#185]
Things seem to be progressing with the massive download and then I get this error.
https://share.getcloudapp.com/v1uWgO19

**Comment by Farscaper** [comment]
Update: I resolved it by using the full build option command after several retries due to my slow Internet. Thankfully, failures did not require starting from fresh. It carried on from where it left off and finally got me going.

**Comment by yuhongsun96** [comment]
Thanks for sharing the update! Also recently we merged 2 of the heavy docker images into a single one so hopefully it cuts the download time by half now
