### ISSUE TITLE
Failed to set provider as default: undefined

### ISSUE THREAD

**Issue by hikmet-demir** [danswer-ai/danswer#1897]
Just pull the repo, I run the docker commands successfully and front-end come alive http://localhost:3000/search 
<img width="1282" alt="image" src="https://github.com/user-attachments/assets/139bd684-3570-4674-bfdc-4c1dff8a4c62">

I'm getting "Failed to set provider as default: undefined", it's quite bad experience tbh. Any mitigation or fixes for this?

**Comment by bfamchon** [comment]
Hello,
Was running the same problem with latest version.
I fix it when seeing that environment variables interpretation was changed and for example, specifying 

`GEN_AI_API_ENDPOINT="https://bfamchon.openai.azure.com/"`
was translated into
`\"https://bfamchon.openai.azure.com/\"`
when passing in requests

Same logic for all variables: `GEN_AI_API_VERSION`, `GEN_AI_API_KEY`...

I see that analyzing request body in network...

Hope it can help you

**Comment by hikmet-demir** [comment]
> 
> Hope it can help you

Thank you very much for the help, but this is breaking for everyone and it needs to be addressed by owners/maintaners of the repo. There are 281 Issues and 58 PR open...
