### ISSUE TITLE
Improve PDF text extraction

### ISSUE THREAD

**Issue by jeremi** [danswer-ai/danswer#1938]
Progress has been made on text extraction from PDF. 
It would be good to integrate a process like the one of https://github.com/VikParuchuri/marker and https://github.com/VikParuchuri/surya.
That would allow the text to be better extracted. I understand that the licence of those projects would not be a good option, but there might be other similar models more open.

**Comment by jeremi** [comment]
I also discovered that could be an option: https://github.com/opendatalab/MinerU

**Comment by emerzon** [comment]
We've been also looking forward to use cloud-based services such as https://azure.microsoft.com/en-us/products/ai-services/ai-document-intelligence or https://aws.amazon.com/textract/
