### ISSUE TITLE
Question: what data is shared with external dependencies (OpenAI)

### ISSUE THREAD

**Issue by pawlik** [danswer-ai/danswer#196]
I can't find this information in readme's. OpenAI API key is required for the Danswer to be able to generate answers, which begs the question: which data from connected services are shared with OpenAI?

**Comment by yuhongsun96** [comment]
It uses OpenAI to generate an answer from the most relevant document sections. So we pass in a prompt and several document sections (could be same document or different documents) and a user query to OpenAI.

We are looking to support local models and Azure OpenAI very soon (there are other open issues and PRs already for those).

Hope that answers the question!
