### ISSUE TITLE
Customize the postgresql login

### ISSUE THREAD

**Issue by Freeconcepteur** [danswer-ai/danswer#1967]
I can't deploy properly when I change the postgresql user and password in the ".env" file.
If I leave:
POSTGRES_USER=postgres
POSTGRES_PASSWORD=password
There is no problem.
How can I customize the postgresql login information?

Thank's for your help.

**Comment by Chillwind132** [comment]
@Freeconcepteur - you may need to update the same variables directly in the backend/danswer/configs/app_configs.py file

**Comment by rkuo-danswer** [comment]
Hi Freeconcepteur, you would need to set these variables on both the client side (which it looks like you've figured out) and the server side as well as update your postgres startup to match.  There are examples of this in deploment/kubernetes/postgres-service-deployment.yaml and secrets.yaml.
