### ISSUE TITLE
Slack Bot unable to reply to other bots

### ISSUE THREAD

**Issue by spagnoloe-capchase** [danswer-ai/danswer#1991]
It seems Danswer Slack Bot is unable to respond to other bot messages, even after selecting the corresponding checkbox.

![image](https://github.com/user-attachments/assets/27e6f2b6-9327-4c7f-afe3-0c0991b655cc)

We have observed this with 2 different Slack Bots:
- [Zendesk](https://support.zendesk.com/hc/en-us/articles/4408833756698-Understanding-and-installing-the-Slack-for-Zendesk-Support-integration) Bot.
- [Zappier](https://zapier.com/apps/slack/integrations?utm_source=partner_slack_integrations&utm_medium=embed_custom_zapier&utm_campaign=slack_zapier_integration) Bot.

After reviewing the logs in our Danswer deployment (currently the community version deployed in a Virtual Machine in Google Cloud Platform), I noticed that Danswer is not able to parse the messages from these bots and captures them as empty '' messages.

`06/27/2024 04:19:15 PM          listener.py  92 : [Channel ID: C02LKB3K6N8] Cannot respond to empty message - skipping`

Example of message

![image](https://github.com/user-attachments/assets/9457c19f-5c86-4185-b5fe-f5f2916b85db)

After reviewing the messages using `slack_sdk` library, the most educated guess is that [this msg variable here](https://github.com/danswer-ai/danswer/blob/8be42a5f985a9463edd29a6ddd54ea56e2c0e75a/backend/danswer/danswerbot/slack/listener.py#L81) gets a None on those Slack messages.

It seems that instead, when the messages come from a bot, the text should be extracted from the attachments. Particularly the title comes from `event.get('attachments', {}).get('text')`, and the content from `(event.get('attachments', {}).get('fields')[0]).get('value')`.

Not sure though if this is the general case for Slack Bots and whether this implementation is acceptable.

More details on this [thread](https://danswer.slack.com/archives/C056265VB1N/p1719496799622419).

**Comment by jorge-sanchez-capchase** [comment]
Could we reopen this issue?
