### ISSUE TITLE
Can't index data from Notion 

### ISSUE THREAD

**Issue by talhelfgott666** [danswer-ai/danswer#1993]
Hey, 
I want to connect notion but can't index data.
Seems like it finds the pages are empty

`
  File "/app/danswer/natural_language_processing/search_nlp_models.py", line 79, in encode
    raise ValueError(f"Empty or missing text for embedding: {texts}")
ValueError: Empty or missing text for embedding: []`

Also:
`07/31/2024 12:12:02 PM indexing_pipeline.py 137 : [Attempt ID: 2] Skipping document with ID ff1c5b71-3021-49d7-8ee1-47b1b978e1b1 as it has neither title nor content`
For each page it's finding

Tried to use in another Notion workspace i have (First i tried in my company's workspace and then my private one).
Deployed the docker-compose on ec2 and then locally on my mac.
Getting the same result. 

Thank you!

**Comment by talhelfgott666** [comment]
No, 
It's also happening in Jira.

Maybe there's a bug?
Maybe it's something i did? 

Help please (:

**Comment by Compy** [comment]
@talhelfgott666 

What was the fix here? I'm running into this when indexing from GitHub or a website. I have ollama set up locally as well.

**Comment by talhelfgott666** [comment]
@Compy 
They deployed a fix. Just pull and re-deploy.

**Comment by Compy** [comment]
> @Compy They deployed a fix. Just pull and re-deploy.

Confirmed fixed in the latest docker pulls! Thanks a bunch!
