### ISSUE TITLE
Google Drive: Can't manage connection in error state

### ISSUE THREAD

**Issue by chrisedington** [danswer-ai/danswer#203]
I'm getting this in the UI. Seems due to the folder scoping being added? After removing volumes and starting again, it worked fine.

<img width="1444" alt="Screenshot 2023-07-18 at 14 29 37" src="https://github.com/danswer-ai/danswer/assets/2725500/14f689e9-ee8b-446a-83b9-27fa144ce635">

<img width="1728" alt="Screenshot 2023-07-18 at 14 27 50" src="https://github.com/danswer-ai/danswer/assets/2725500/812d2e97-a17e-44b8-b80e-1f314475cecb">

<img width="1727" alt="Screenshot 2023-07-18 at 15 00 05" src="https://github.com/danswer-ai/danswer/assets/2725500/66722873-e773-4ab8-81f9-1a07c1c0b948">

**Comment by Weves** [comment]
Thanks for the heads up! Fixed in https://github.com/danswer-ai/danswer/pull/235.
