### ISSUE TITLE
After recent update: Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by gabilanbrc** [danswer-ai/danswer#2127]
Hi Team
I have recently updated using git pull and `docker compose -f docker-compose.gpu-dev.yml -p danswer-stack up -d --force-recreate` 
When starting up, I'm getting 

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)

on the danswer-stack-inference_model_server-1

I have seen in Slack others having the same issue. Any recommendation?

**Comment by hagen-danswer** [comment]
Hey, thanks for the heads up! We just pushed a fix with this PR:

[https://github.com/danswer-ai/danswer/pull/2135](https://github.com/danswer-ai/danswer/pull/2135)
