### ISSUE TITLE
Local File PDF Support

### ISSUE THREAD

**Issue by mozeqiu123** [danswer-ai/danswer#214]
.txt文件现在使用太局限了，可以支持PDF吗

**Comment by yuhongsun96** [comment]
For english audience, I believe this request is "Local PDF support", renaming as such

**Comment by yuhongsun96** [comment]
Original title: 功能请求：上传文件支持PDF文件

**Comment by yuhongsun96** [comment]
Was done a bit ago, never closed the ticket, closing now
