### ISSUE TITLE
KeyError while attempting to delete Slack connector

### ISSUE THREAD

**Issue by brianrudolf** [danswer-ai/danswer#2171]
This error popped up after I attempted to delete a paused Slack connector that was ingesting multiple channels. Currently Danswer is unable to delete this connector as it keeps hitting this same error - after spending an hour going through ~5000 documents.

Sequence of events with the connector:
- Create connector targeting multiple channels
- Pause ingestion
- Delete connector

Is it possible there is some data corruption? Is there a manual way to delete data from Vespa and the index volume?

```
Traceback (most recent call last):
  File "/app/danswer/background/indexing/run_indexing.py", line 216, in _run_indexing
    new_docs, total_batch_chunks = indexing_pipeline(
                                   ^^^^^^^^^^^^^^^^^^
  File "/app/danswer/utils/timing.py", line 31, in wrapped_func
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/indexing/indexing_pipeline.py", line 214, in index_doc_batch
    access_aware_chunks = [
                          ^
  File "/app/danswer/indexing/indexing_pipeline.py", line 217, in <listcomp>
    access=document_id_to_access_info[chunk.source_document.id],
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'C0700GRSS2Y__1724089922.846989'
```

**Comment by brianrudolf** [comment]
This was blocking me, so I ended up having to use the force delete script to remove this connector and its data.

**Comment by rkuo-danswer** [comment]
Thanks Brian.  We're putting in a PR to allow indexing to continue safely if this error happens.  https://github.com/danswer-ai/danswer/pull/2309

**Comment by yuhongsun96** [comment]
Hey Brian! Thanks for pointing this out!

By the way, curious to know how you came across Danswer and what you're using it for! Would you be down to chat some time? Here's my Cal if you have some time: https://cal.com/yuhongsun/15min
