### ISSUE TITLE
 confluence space cannot be imported

### ISSUE THREAD

**Issue by Xu99999** [danswer-ai/danswer#220]
![image](https://github.com/danswer-ai/danswer/assets/111261378/e0565022-e2a3-4a05-bdc0-b51caf93cedf)

**Comment by Xu99999** [comment]
Neither the privatized deployment nor the public network can be imported normally

**Comment by Xu99999** [comment]
Yes, and the code only supports confluence on the public network, the URL of the private deployment is completely different from the URL of the public network
`if ".atlassian.net/wiki/spaces/" not in wiki_url:
        raise ValueError(
            "Not a valid Confluence Wiki Link, unable to extract wiki base and space names"
        )`

**Comment by yuhongsun96** [comment]
Sorry for the very delayed response! If you're still running into this, we have added better logging/error tracking. Any luck getting things to work?

**Comment by Xu99999** [comment]
import error
1 validation error for CCPairFullInfo name none is not an allowed value (type=type_error.none.not_allowed)

Atlassian Confluence 7.19.9(local DC)

**Comment by Xu99999** [comment]
> Sorry for the very delayed response! If you're still running into this, we have added better logging/error tracking. Any luck getting things to work?

After the update, I tested that the local confluence dc can be imported. Thanks
