### ISSUE TITLE
Extract metadata from PDF

### ISSUE THREAD

**Issue by jeremi** [danswer-ai/danswer#2230]
It is quite an issue to not be able to at least tag PDFs when importing with connectors.

What about changing this function:
[def pdf_to_text(file: IO[Any], pdf_pass: str | None = None) -> str:](https://github.com/danswer-ai/danswer/blob/1bc899cc6787d948db2d207b3332f38ada19557d/backend/danswer/file_processing/extract_file_text.py#L180)

to return the metadata the same way as:

https://github.com/danswer-ai/danswer/blob/1bc899cc6787d948db2d207b3332f38ada19557d/backend/danswer/file_processing/extract_file_text.py#L148-L153****

`pypdf` as a feature to extract them:
https://pypdf.readthedocs.io/en/stable/user/metadata.html

That could allow to pre-process the PDFs to add the metadata we need.

**Comment by pablodanswer** [comment]
Great idea! Added in https://github.com/danswer-ai/danswer/pull/2278
