### ISSUE TITLE
Rework the "set as default" logic of LLM model providers: default model instead of default LLM provider

### ISSUE THREAD

**Issue by Hurricane31337** [danswer-ai/danswer#2257]
I really like that it's already possible to add LLM providers more than once, for example to have two OpenAI API keys or multiple Ollama servers with different models. However with the current "set as default" logic, I can't set the default of the large model and fast one (lighter flows like `LLM Chunk Filter`) individually. In my case, I have an Ollama instance that hosts "mixtral:8x22b-instruct-v0.1-q4_0" but it can't host another fast model due to limited VRAM. Therefore I can't use my Ollama instance for RAG at all and have to keep using OpenAI completely. It would be no problem for me to host another Ollama instance with the small model on another server, but that wouldn't help with the current "set as default".

I suggest that we could have a separate "set default model" popup that would list all models of all LLM providers combined (just like in the chat) and there you could set the default of each task individually (maybe even more detailed, e.g. default for chat, default for search, default for chunk filter, ...). This would solve my problem plus be much more transparent and configurable.

**Comment by pablodanswer** [comment]
@Hurricane31337 This is a fantastic idea! I think having some more fine-grained access for your controls and making defaults inter-operable between providers is a no-brainer. Will surface to the team.

**Comment by Hurricane31337** [comment]
Awesome, thanks! I’m really looking forward to the change, so I can use Danswer completely offline! 🤩
