### ISSUE TITLE
Saving "Search Settings" throws an error

### ISSUE THREAD

**Issue by DavidReinberger** [danswer-ai/danswer#2269]
While trying to save Search settings it throws an error even though I've filled in all the required fields. `rerank_api_key` is missing in the sent object.

The issue is visible [here](https://github.com/danswer-ai/danswer/blob/1734a4a18c65c1d1f4baa7970d025105154ac470/web/src/app/admin/embeddings/pages/EmbeddingFormPage.tsx#L46-L51).

**Comment by pablodanswer** [comment]
Resolved with https://github.com/danswer-ai/danswer/pull/2259
