### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by MaroeSHE** [danswer-ai/danswer#2331]
When trying to do the docker compose comand of the Danswer doc quickstart page I have the following error :

Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Does anyone know how to solve the error? 

Thank you ! 😄

**Comment by rkuo-danswer** [comment]
This looks likely to be a temporary networking issue or possibly proxy/firewall issue within your installation environment/network.

**Comment by MaroeSHE** [comment]
Thank you very much, it was a proxy related issue indeed. 

I am wondering if the errors (see the screens below) at the API key step come from this same issue. 
What do you think?

![Capture](https://github.com/user-attachments/assets/276dc5f5-fdb2-4485-99ae-5db9807d3a54)
![Capture2](https://github.com/user-attachments/assets/a9622ec7-ac07-4e9d-822d-2cb2f46d72ca)
![Capture3](https://github.com/user-attachments/assets/73c7b06b-2ff6-497b-9703-2d07a4cc7ec7)
![Capture4](https://github.com/user-attachments/assets/80f2fee1-14ab-469a-84cc-ea23b19bca8a)

**Comment by rkuo-danswer** [comment]
Yes, it looks like a similar issue.  I'm going to go ahead and close this out since it seems to be an issue outside of danswer, but please feel free to report any danswer related issues here or visit some of the community related slack or discord channels for general help from the community.
