### ISSUE TITLE
Danswer as Backend?

### ISSUE THREAD

**Issue by emorling** [danswer-ai/danswer#2339]
Great project! Quick question:

is it possible to use self hosted Danswer as a backend service for another product? When I looked at the docs, it seems like the API is fairly barebones if we wanted to expose functionality to another front end experience? Do you have any thoughts on that? Thanks

**Comment by pablodanswer** [comment]
This is certainly possible @emorling! While our focus is on making the core Danswer experience as seamless as possible, we're working on making the APIs more developer friendly so you can take advantage of al the indexed content and functionality we have under the hood.

All that to say, yes- and stay tuned for more!
