### ISSUE TITLE
CORS Wildcard is security sensitive

### ISSUE THREAD

**Issue by se-wo** [danswer-ai/danswer#2444]
Allowing CORS from all origins by default is concerning in terms of security. Moreover the current settings do not work as the developer intended it. All major webbrowser vendors disable the combination of an origin wildcard with `Access-Control-Allow-Credentials`. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#access-control-allow-origin) or [OWASP](https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/11-Client-side_Testing/07-Testing_Cross_Origin_Resource_Sharing)  for reference.
In this case the potential risk is to a large extend mitigated by modern webbrowsers as they disregard the combination of those settings. Otherwise third party websites could potentially steal information if a user is already authenticated via a cookie. Nevertheless not adding an explicit allow list leaves a risk for unauthenticated instances or misuse of API keys.

https://github.com/danswer-ai/danswer/blob/430c9a47d71d40c1293d304719f7ca329baec456/backend/danswer/main.py#L592-L598

**Comment by pablodanswer** [comment]
Addressed by https://github.com/danswer-ai/danswer/pull/2449
