### ISSUE TITLE
Has no one responded to open source?

### ISSUE THREAD

**Issue by zhaojing1987** [danswer-ai/danswer#2565]
When I finish the installation and come to this page, enter the relevant data, and click the enable button, there is no response?
![image](https://github.com/user-attachments/assets/01f9e714-8f28-4d50-ba77-7dde42c7d07d)

The console keeps reporting errors:
![image](https://github.com/user-attachments/assets/c437ddd2-6bc3-4a28-9cf3-7678b1cd1700)

But in:/admin/configuration/lm configuration, it is normal

![image](https://github.com/user-attachments/assets/0d00a519-db9e-4b2b-87ac-b57a8dbecf2f)

**Comment by pablodanswer** [comment]
Sorry you're running into that! If you refresh the page, the modal should go away. We'll make this user path clearer in the next release.
