### ISSUE TITLE
Introduce hyphen between docker  compose command 

### ISSUE THREAD

**Issue by Saksham1611** [danswer-ai/danswer#257]
`docker compose` command  wasn't working . Was giving the below error (https://github.com/docker/compose/issues/8630) . 
Solution was to introduce an hyphen` in between 

P.S : this command solved the issue for me . 
(https://github.com/danswer-ai/danswer/blob/main/deployment/README.md)
`docker-compose -f docker-compose.dev.yml -p danswer-stack up -d --pull always --force-recreate`

**Comment by yuhongsun96** [comment]
docker-compose and docker compose are 2 separate commands. docker-compose (with dash) is a standalone which docker eventually incorporated into their standard CLI so it became available as docker compose (with space). If docker compose (with space) isn't working, most likely you're on too old of a docker version.
