### ISSUE TITLE
GPL-licenced libraries dependencies

### ISSUE THREAD

**Issue by marcinbienkowski** [danswer-ai/danswer#2587]
Current versions of Danswer depend on the following Python libraries, which are licensed under the GPL:

```
rt==3.1.2
zenpy==2.0.41
ultimate_sitemap_parser==0.5
```

Isn't this problematic for the `ee` version, which uses a non-GPL-compatible licence? See, e.g., https://www.gnu.org/licenses/gpl-faq.en.html#LinkingWithGPL

**Comment by yuhongsun96** [comment]
Done! Thanks for pointing it out!
