### ISSUE TITLE
docs: how to configure open source LLMs in place of Open AI GPT?

### ISSUE THREAD

**Issue by freitzzz** [danswer-ai/danswer#261]
So the GitHub readme states that there is a way to use open source LLMs instead of OpenAI GPT:

> Option to use Opensource LLMs like Orca, Falcon etc. in place of OpenAI GPT.

How can I configure it in danswer? It always prompts me to insert a OpenAI key and I don't find an option to select an open source LLM

**Comment by freitzzz** [comment]
update: on discord the maintainers said it will come in a near release!

**Comment by yuhongsun96** [comment]
Done! Thanks for your patience: https://docs.danswer.dev/gen_ai_configs/overview
