### ISSUE TITLE
i build with latest git clone command and show me Danswer version: 0.3-dev but we have 0.6.0 lastest version

### ISSUE THREAD

**Issue by johnfelipe** [danswer-ai/danswer#2684]
![SNAG-0385](https://github.com/user-attachments/assets/87a5f817-2259-4e36-b598-c154c3be05b6)

how solve this?

**Comment by pablodanswer** [comment]
Looks like an issue on our end- images default to 0.3-dev if not specified otherwise. Fix coming soon
