### ISSUE TITLE
No matching document can be found.

### ISSUE THREAD

**Issue by ws1hope** [danswer-ai/danswer#272]
I use keyword search, when the uploaded document is in Chinese, and ask a question in Chinese, it will show that "no matching document can be found", is this the reason that the sentence-transformer and cross-encoder models have poor support for Chinese and chunk stategy? Do you have any suggestions for solving this problem, thank you very much!

**Comment by ws1hope** [comment]
Is it normal to open the port of typesense to show "{ "message": "Not Found"}"?

**Comment by Weves** [comment]
Currently, Danswer is designed to work for English documents :( If you want to select your own models which are trained on Chinese, then you can look at https://github.com/danswer-ai/danswer/blob/main/backend/danswer/configs/model_configs.py#L15. 

We unfortunately don't have the expertise to handle supporting Chinese, so closing this Issue for now. Let us know if you're able to get this working!
