### ISSUE TITLE
Clean danswer/danswer-web-server:v2.0.12 Docker image tag

### ISSUE THREAD

**Issue by vlaborie** [danswer-ai/danswer#2894]
Hello,

There is a [v2.0.12](https://hub.docker.com/layers/danswer/danswer-web-server/v2.0.12/images/sha256-5d474d82ce6d8281a27752484f6ff7e8efe13c73f64dab0d361842ab5959dc34?context=explore) Docker image tag for `danswer/danswer-web-server`.

This seem to be a tag error when the version `v0.2.12` was out.

This confuse auto update tools like [Renovate](https://docs.renovatebot.com/), can you delete this tag ?

Thank's,

**Comment by rkuo-danswer** [comment]
Tag removed. Thanks for reporting!
