### ISSUE TITLE
Feature: Add support for Microsoft Office 365

### ISSUE THREAD

**Issue by ncecere** [danswer-ai/danswer#2927]
I think adding support for the Azure/O365 products would help your business and customer base alot.  Microsoft is used by alot of Higher Educational institutions. 

## Connectors:

- Storage: OneDrive
- Storage: Azure Blob
- Wiki: SharePoint

## Custom Assistant
- Teams Bot (Like theSlack Bot)

**Comment by pablodanswer** [comment]
We do have a Sharepoint connector but this is a great recommendation! A Teams bot is something certainly on the roadmap and I think Azure has a great suite of products that we'd like to integrate with.
