### ISSUE TITLE
how can put answers in spanish - same like questions - using gemini 1.5 pro latest model?

### ISSUE THREAD

**Issue by johnfelipe** [danswer-ai/danswer#3086]
![SNAG-0192](https://github.com/user-attachments/assets/33495fcc-8b0d-4ab0-ac54-2bcc9eec9b3b)

with gpt and claude 3.5, answer is in same language of question

how can solve that?

**Comment by 4entertainment** [comment]
Hi @johnfelipe. I don't know how to fix your problem but i have a question for you. I would appreciate it if you could answer.
I would like to perform a query expansion task.

The query will be in Italian, while the documents are originally stored in English. Despite the query being in Italian, the retrieval should be conducted on the English documents, and the final LLM response should be in English as well.

What changes should I make in the source code or UI to achieve this? Thank you.

**Comment by johnfelipe** [comment]
Issue is
Pdf is in Spanish 
Question is in Spanish 
But in Gemini answers is English
How can do that in Gemini, because all other llms answer in Spanish.

**Comment by 4entertainment** [comment]
You can review the assistant prompt. You might try guiding it with prompt engineering in this way. The instruction you write should contain a phrase like "Speak only in Spanish."

On the other hand, could you help me understand what I need to modify or what steps I should take in the source code to achieve a similar result as in the operation above?
