### ISSUE TITLE
Failed to load connectors (ARM Version)

### ISSUE THREAD

**Issue by cevinov** [danswer-ai/danswer#309]
Hello Everyone,

I have a plan to use Danswer.AI with my bookstack so that I can get more information from it. Where Bookstack will be the source of truth, but the problem is I can't set up a Bookstack connector. It says an error message: "Failed to load connectors."
![failed-load-connector](https://github.com/danswer-ai/danswer/assets/94840989/def6b323-601f-4f34-bdd9-9ebd15e0634b)
![startup-failed](https://github.com/danswer-ai/danswer/assets/94840989/fb78e221-849a-4c0e-9890-ca5550bf222b)

I attach the log files after the deployment from danswer-api-server, which is the backend.
[_danswer-stack-api_server-1_logs.txt](https://github.com/danswer-ai/danswer/files/12361486/_danswer-stack-api_server-1_logs.txt)

Please help. Thanks.

**Comment by Weves** [comment]
Hey @cevinov! Is the Qdrant container up and running?

**Comment by cevinov** [comment]
Hello@Weves , yes its up and running

**Comment by yuhongsun96** [comment]
Hey, could you try again, we've changed the default VectorDB to Vespa anyway so hopefully it works for you now?

**Comment by cevinov** [comment]
Hello @yuhongsun96, 

Thanks it works well now. Good job
