### ISSUE TITLE
Unable to Install Playwright When Running Locally

### ISSUE THREAD

**Issue by Mutai-Gilbert** [danswer-ai/danswer#3163]
Description

While setting up the project and attempting to install Playwright in the local environment, I encountered an issue where the playwright command was not recognized, even after activating the Python virtual environment.

Steps to Reproduce

1. Clone the repository and navigate to the project directory.
2. Set up the Python virtual environment and activate it:

`python3 -m venv .venv
source .venv/bin/activate
`
3. Attempt to install Playwright and its required browsers using the command:
`playwright install
`
4. Receive the error:
`zsh: command not found: playwright
`

Resolution

The following steps resolved the issue:

1. Install Playwright explicitly using pip:

`pip install playwright
`
2. Verify the installation:

`playwright --version
`
Output: Version 1.48.0
3. After the installation, I was able to run playwright install successfully.
Expected Behavior

Running playwright install directly should install Playwright and its dependencies without requiring manual installation via pip.

Environment

OS: macOS 11+
Shell: zsh
Python Version: 3.11
Playwright Version: 1.48.0
Suggestions

Update the documentation to specify that users might need to install Playwright via pip if the command isn't recognized initially.

Let me know if you need additional details! 😊

**Comment by rkuo-danswer** [comment]
Hi Mutai,

The basic deployment is done using docker compose and the docker files handle playwright installation into the docker images when building them.

If running services directly from source, the install steps for playwright are mentioned in the CONTRIBUTING guide.

https://github.com/danswer-ai/danswer/blob/main/CONTRIBUTING.md
