### ISSUE TITLE
Cannot create Slackbots anymore

### ISSUE THREAD

**Issue by ahmadassaf** [danswer-ai/danswer#3171]
Whenever I try to create a new Slackbot; past the token screen I keep getting the following:

```
due to Something went wrong :( Failed to fetch Slack Bot 3%7D: [{'type': 'int_parsing', 'loc': ('path', 'slack_bot_id'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': 'NaN', 'url': 'https://errors.pydantic.dev/2.8/v/int_parsing'}]
```

**Comment by ahmadassaf** [comment]
looking at the generated URL after I try to create any new bot I notice `7%7D` which basically encodes a `}` after the number id (in this case 7) which is causing the error

**Comment by pablodanswer** [comment]
This should be fixed in this PR: https://github.com/danswer-ai/danswer/pull/3179

Apologies for the inconvenience!

**Comment by ahmadassaf** [comment]
Whilst now I can create a new Slackbot; it seems that there is no way for me to configure it. Something changed in the creation flow and it seems its broken

<img width="1201" alt="image" src="https://github.com/user-attachments/assets/24f2d07e-8c53-4c83-8e2b-e9e65dad344b">
> After creation I come back to this screen; there was no "configuration" screen

If I click on add Slackbot configuration I get redirected to create a **new** bot

<img width="1368" alt="image" src="https://github.com/user-attachments/assets/deba6677-53b2-42d0-8c44-387819658310">
