### ISSUE TITLE
Prem Integration: supports multiple models and vectorstores

### ISSUE THREAD

**Issue by filopedraz** [danswer-ai/danswer#334]
Enabling [Prem](https://github.com/premAI-io/prem-app) gives out-of-the-box all the models packaged in the [Prem ecosystem](https://registry.premai.io/).

### Benefits

- Avoids relying on OpenAI dependency enabling an end-to-end self-hosted solution for enterprises very focused on data ownership.
- It doesn't change the current architecture. No breaking changes are required. All the Prem services expose the same APIs as OpenAI. 

I would love to contribute, I am looking for an ACK on the direction and availability to merge, so I can start working on it if there is interest.

**Comment by yuhongsun96** [comment]
Hey, could you explain a bit more on the need for this? We have supported for plug and play LLMs already (and recently added LangChain supported models as well)

**Comment by filopedraz** [comment]
Yep, I saw you have included LangChain support recently. From what I saw you included LangChain for `Chat` integration, but not for Emebeddings. When you include LangChain integration for Embeddings too you can close this issue. All the [Prem Services](https://registry.premai.io/) expose same APIs as OpenAI for both Chat and Embeddings.

**Comment by yuhongsun96** [comment]
Going to close this one, apologies. We have a pretty custom pipeline that uses several NLP models in conjunction at different stages so supporting plug and play solutions can cause unexpected breakages in functionality that may not even get caught but will degrade user experience. Will keep an eye out for future integration opportunities.

And huge thanks for pointing this out as an option!
