### ISSUE TITLE
Will be great if you can choose the set of information that you want to search the content of

### ISSUE THREAD

**Issue by jignnsd** [danswer-ai/danswer#338]
Hey guys, many thanks for an awesome project. I think that will be greatly useful if you can add the possibility to choose the information (documents) to ask the question to. Like making a list of datasets, each of these can have, for example different folder in google drive, so the question will only be answered with that dataset, also the keyword search will only be searched within that dataset. This is necessary because sometimes you know the dataset where you want to interact with, if you interact with all the information sometimes will give a lot of irrelevant answers and sources. My idea is that you can add datasets, each with the appropriate information (google drive folder). Then in the ask question area, you can choose what dataset or datasets that you want to use (could be a list of datasets with check selection). 
So the question or keyword search will only be made to the check marked dataset(s). Many thanks

**Comment by yuhongsun96** [comment]
Very valid feature request! We will get around to this after some higher priority items like support chat, more flexible prompting options, and better admin features

Thanks for the suggestion!

**Comment by yuhongsun96** [comment]
Hello! Document-Sets were added a little bit ago as a feature, you can add different connectors to a document set and filter by document set via the UI. You can also assign document sets to SlackBot configs now if that's your preferred interface.

<img width="2223" alt="image" src="https://github.com/danswer-ai/danswer/assets/32520769/9c32e36f-b0ee-4399-9dd0-5c55fc1a168a">

Hope you like it!
