### ISSUE TITLE
Google drive connector PyCryptodome is required for AES algorithm if encrypted pdf found

### ISSUE THREAD

**Issue by YoranSys** [danswer-ai/danswer#353]
On Google drive connector there is an error if there is encrypted pdf : 

- PyCryptodome is required for AES algorithm

Solution skip encrypted file: 
```git-diff
--- a/backend/danswer/connectors/google_drive/connector.py
+++ b/backend/danswer/connectors/google_drive/connector.py
@@ -290,7 +290,8 @@ def extract_text(file: dict[str, str], service: discovery.Resource) -> str:
         response = service.files().get_media(fileId=file["id"]).execute()
         pdf_stream = io.BytesIO(response)
         pdf_reader = PdfReader(pdf_stream)
-        return "\n".join(page.extract_text() for page in pdf_reader.pages)
+        if not pdf_reader.is_encrypted:
+            return "\n".join(page.extract_text() for page in pdf_reader.pages)
 
 ```

**Comment by yuhongsun96** [comment]
Hey! This looks good :+1: 

Would you care to create a PR? We'd love to give you credit for locating/fixing the issue! If you could add a logger.warning as well detailing what's happened in case users wonder why only the title exists, then they can check the logs to see.

Thanks for your help with this one
