### ISSUE TITLE
Slack connector - psycopg2.errors.NotNullViolation) null value in column "id" of relation "document" violates not-null constraint

### ISSUE THREAD

**Issue by YoranSys** [danswer-ai/danswer#354]
This error appears during slack indexing:  
```
(psycopg2.errors.NotNullViolation) null value in column "id" of relation "document" violates not-null constraint
DETAIL:  Failing row contains (null, 0, f, null, null).

[SQL: INSERT INTO document (boost, hidden) VALUES (%(boost)s, %(hidden)s) ON CONFLICT DO NOTHING]
[parameters: {'boost': 0, 'hidden': False}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
````

![image](https://github.com/danswer-ai/danswer/assets/11197007/a2e97717-3491-4290-ae47-f724d4fd2f05)

**Comment by Weves** [comment]
Hey @YoranSys! Thanks for bringing up this issue. Can you paste the surrounding logs if you still have them? Specifically, the line(s) starting / surrounding: `Failed to upsert insertion records from vector index for documents`.

**Comment by Weves** [comment]
Ah, I see. Very strange that `insert(DbDocument).values([])` still tries to insert anything into the DB 🤔  

Fixed this here: https://github.com/danswer-ai/danswer/pull/364
