### ISSUE TITLE
AI Response Display Issue - Lack of Proper Formatting for Returns and Code

### ISSUE THREAD

**Issue by YoranSys** [danswer-ai/danswer#376]
I have encountered an issue with the AI response display in the Danswer application. The AI responses are displayed without respecting return or code formatting. This leads to a lack of proper structure and readability in the responses, which is not ideal for users who rely on these responses for information. This issue has been observed while using Danswer on both local and Kubernetes deployments.

Steps to reproduce:

    Deploy the Danswer application locally or on Kubernetes following the instructions in the [Deployment documentation](https://github.com/danswer-ai/danswer/#deployment).
    Connect to a common tool (e.g., Slack, GitHub, Confluence) as mentioned in the [Features](https://github.com/danswer-ai/danswer/#features).
    Ask a natural language question against internal documents.
    Observe the AI response.

Expected Behavior:

The AI response should properly format returns and code for readability and structure, providing reliable answers backed by quotes and references from the source material.

Actual Behavior:

The AI response is displayed as a continuous block of text without respecting return or code formatting.

Any help in resolving this issue would be greatly appreciated.

**Comment by Weves** [comment]
@YoranSys got it, yea this is a great suggestion. Will add it to the backlog for us, shouldn't be a large change. Will update here once complete.

**Comment by Weves** [comment]
Completed in https://github.com/danswer-ai/danswer/pull/437!
