### ISSUE TITLE
ERROR: missing signature key    how to solute it

### ISSUE THREAD

**Issue by ratel-hu** [danswer-ai/danswer#394]
how to solve it
codes:
docker-compose -f docker-compose.dev.yml -p danswer-stack up -d --build --force-recreate

**Comment by Weves** [comment]
@ratel-hu what's the error message you're seeing?

**Comment by ratel-hu** [comment]
> @ratel-hu what's the error message you're seeing?

@Weves Thank you for your attention，It's only because docker version too low. It's solved

**Comment by ratel-hu** [comment]
nothing
