### ISSUE TITLE
Danswer Chat

### ISSUE THREAD

**Issue by yuhongsun96** [danswer-ai/danswer#412]
Chat with retrieval via Danswer system.
- Advanced context retrieval, multiple chunks per search
- Maintain user/system/retrieval context during Chat
- LLM to decide if it needs to fetch more context at each step
- Multi-session support
- Chat related metrics

**Comment by devrimcavusoglu** [comment]
Any ETA on this chat/conversation feature ?

**Comment by yuhongsun96** [comment]
Hello! Hopefully in 2 weeks. This week we're focusing on recommending Subject Matter Experts for the cases where the answer you want isn't in the docs. Then we're finalizing chat the week after. Most of the work is already done but we need to tidy some things up :)

**Comment by fan-wen** [comment]
Can't wait for the chat/conversation feature!!!

**Comment by yuhongsun96** [comment]
Finished this a bit ago, forgot to update the issue
