### ISSUE TITLE
Personas and Knowledge Sets

### ISSUE THREAD

**Issue by Weves** [danswer-ai/danswer#439]
- Allow the creation of groups of documents
    - These groups can include just certain documents from any given connector
- Personas can have different prompts to serve different functions. Ie. Customer Support, Engineering Team member, etc.

**Comment by tomad02** [comment]
Hi. When is this feature planned to be released ?

**Comment by Weves** [comment]
Hey @tomad02! We released groups of documents (we are currently calling them "document sets") a couple weeks back! Regarding custom prompts, we don't have an exact timeline, but likely in the next couple weeks.

Which one of these two were you most interested in?

**Comment by tomad02** [comment]
I was interested in "document sets". Yes. I see now the feature works fine!

**Comment by yuhongsun96** [comment]
Done!
