### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by cometothed4rkside** [danswer-ai/danswer#451]
Installation should be more simpler. I tried a lot for Windows but I couldn't install it.

**Comment by modist** [comment]
1. install docker https://docs.docker.com/desktop/install/windows-install/
2. install GIT https://gitforwindows.org/
3. follow https://docs.danswer.dev/quickstart

**Comment by rkuo-danswer** [comment]
Closing this issue due to age and lack of specifics.  As far we know Docker installs should at least spin up, so please report back if you have any actionable Danswer issues once a docker compose is up and running.  Thanks!
