### ISSUE TITLE
Answer source of Notion is always the same page

### ISSUE THREAD

**Issue by MuratDoganer** [danswer-ai/danswer#465]
Hey, 

I've just experience an issue where if Danswer finds the answer in Notion, instead of linked the page as the source, it will link the parent page as the source rather than the page itself 

So everything comes out looking like: ACME Homepage

No matter where the content is actually located. I figured it might be because I added the connector to the parent page, then allowed Notion to add it to all the pages within it.

Would I need to individually add the connector to _every_ page one by one?

**Comment by Weves** [comment]
Hey @MuratDoganer!

Can you share which version of Danswer you're running into this issue with? Around a week ago we made some changes to the notion connector (https://github.com/danswer-ai/danswer/pull/440/files) which I think should address this.

**Comment by MuratDoganer** [comment]
Before I do, is there a recommended way to upgrade?

**Comment by Weves** [comment]
@MuratDoganer you can upgrade by just pulling in the latest version of Danswer with `git pull` (assuming you're on the main branch) + re-running the command you used to start things up (e.g. `docker compose -f docker-compose.dev.yml -p danswer-stack up -d --pull always`)!

Let me know if this works for you.
