### ISSUE TITLE
Incorrect API key provided: dummy_ap*_key. 

### ISSUE THREAD

**Issue by GalensGan** [danswer-ai/danswer#533]
I started Danswer with docker by `docker compose -f docker-compose.dev.yml -p danswer-stack up -d --build --force-recreate`，when I ask questions in UI，I got the error: `Incorrect API key provided: dummy_ap*_key. You can find your API key at https://platform.openai.com/account/api-keys.`

In this guide [OpenAI Options](https://docs.danswer.dev/gen_ai_configs/open_ai) said `The default Danswer model is GPT-3.5-Turbo so if you wish to use this, there’s no need to change anything`. I have read the [issue: openai.error.AuthenticationError: Incorrect API key provided](#471)，but it not works for me

How can I run well with default settings?

**Comment by yuhongsun96** [comment]
Have you added your OpenAI API key via the UI?

**Comment by GalensGan** [comment]
Never done. when I input OpenAI API key in admin panel and click Submit, it always prompts `Invalid API key provided`
![image](https://github.com/danswer-ai/danswer/assets/45629076/988a406c-48b5-492a-8224-867a78e9c1bf)

**Comment by yuhongsun96** [comment]
The key probably doesn't have any credits associated to it.
https://github.com/danswer-ai/danswer/blob/main/backend/scripts/test-openapi-key.py
Can you try this standalone script? (you just need to have python and pip install openai)

This is a minimal test to see if your key is actually useable.

**Comment by GalensGan** [comment]
After verifying with test-openapi-key.py, it returns success.
![image](https://github.com/danswer-ai/danswer/assets/45629076/aa46d6ac-3c30-4317-a2af-10873d7a4037)
the model version is `text-davinci-003`

in `.env` file， I change the environment below :
```
# Insert your OpenAI API key here If not provided here, UI will prompt on setup.
# This env variable takes precedence over UI settings.
# This is part of my key
GEN_AI_API_KEY=sk-5hspfjRzyCvk6MI8icEKT3Bl
# Choose between "openai-chat-completion" and "openai-completion"
INTERNAL_MODEL_VERSION=openai-chat-completion
# Use a valid model for the choice above, consult https://platform.openai.com/docs/models/model-endpoint-compatibility
GEN_AI_MODEL_VERSION=text-davinci-003
```

However, danswer still asks me to input api key and prompts error with `Invalid API key provided`

**Comment by GalensGan** [comment]
I know why the error comes，in the api_server container log，it shows `llm_utils.py  50 : GenAI API key failed for the following reason: This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?`

Thank you very much!
