### ISSUE TITLE
Docker build issues with web Dockerfile since 0.2.5.4 and 0.2.5.5 and above(?)

### ISSUE THREAD

**Issue by voarsh2** [danswer-ai/danswer#669]
I've started getting build errors.
[plan-70713346-FRON-1.log](https://github.com/danswer-ai/danswer/files/13223780/plan-70713346-FRON-1.log)

```

#13 [builder 4/4] RUN npm run build
--
01-Nov-2023 05:31:33 | #13 4.694
01-Nov-2023 05:31:33 | #13 4.694 > qa@0.1.0 build
01-Nov-2023 05:31:33 | #13 4.694 > next build
01-Nov-2023 05:31:33 | #13 4.694
01-Nov-2023 05:31:37 | #13 8.535    ▲ Next.js 14.0.0
01-Nov-2023 05:31:37 | #13 8.535
01-Nov-2023 05:31:37 | #13 8.535    Creating an optimized production build ...
01-Nov-2023 05:31:58 | #13 29.49 npm notice
01-Nov-2023 05:31:58 | #13 29.49 npm notice New minor version of npm available! 10.1.0 -> 10.2.2
01-Nov-2023 05:31:58 | #13 29.49 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.2>
01-Nov-2023 05:31:58 | #13 29.49 npm notice Run `npm install -g npm@10.2.2` to update!
01-Nov-2023 05:31:58 | #13 29.49 npm notice
01-Nov-2023 05:31:58 | #13 DONE 29.8s
01-Nov-2023 05:32:02 |  
01-Nov-2023 05:32:02 | #14 [runner 2/7] RUN rm -rf /usr/local/lib/node_modules
01-Nov-2023 05:32:02 | #14 CACHED
01-Nov-2023 05:32:02 |  
01-Nov-2023 05:32:02 | #15 [runner 3/7] RUN addgroup --system --gid 1001 nodejs
01-Nov-2023 05:32:02 | #15 CACHED
01-Nov-2023 05:32:02 |  
01-Nov-2023 05:32:02 | #16 [runner 4/7] RUN adduser --system --uid 1001 nextjs
01-Nov-2023 05:32:02 | #16 CACHED
01-Nov-2023 05:32:02 |  
01-Nov-2023 05:32:02 | #17 [runner 5/7] COPY --from=builder /app/public ./public
01-Nov-2023 05:32:02 | #17 CACHED
01-Nov-2023 05:32:02 |  
01-Nov-2023 05:32:02 | #18 [runner 6/7] COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
01-Nov-2023 05:32:02 | #18 CACHED
01-Nov-2023 05:32:02 |  
01-Nov-2023 05:32:02 | #19 [runner 7/7] COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
01-Nov-2023 05:32:02 | #19 ERROR: failed to calculate checksum of ref 976903dd-8749-4290-bbc9-a81f48c9a4c6::f56zp0oxxaj1rea8lwuhlqmv2: "/app/.next/static": not found
01-Nov-2023 05:32:02 | ------
01-Nov-2023 05:32:02 | > [runner 7/7] COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static:
01-Nov-2023 05:32:02 | ------
01-Nov-2023 05:32:02 | Dockerfile:61
01-Nov-2023 05:32:02 | --------------------
01-Nov-2023 05:32:02 | 59 \|     # https://nextjs.org/docs/advanced-features/output-file-tracing
01-Nov-2023 05:32:02 | 60 \|     COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
01-Nov-2023 05:32:02 | 61 \| >>> COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
01-Nov-2023 05:32:02 | 62 \|
01-Nov-2023 05:32:02 | 63 \|     # Environment variables must be redefined at run time
01-Nov-2023 05:32:02 | --------------------
01-Nov-2023 05:32:02 | ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 976903dd-8749-4290-bbc9-a81f48c9a4c6::f56zp0oxxaj1rea8lwuhlqmv2: "/app/.next/static": not found
```

The last build I ran that worked from web Dockerfile was this commit fad311282b380e58e9ed9fdea27f0c3e67a7c7cc (0.2.5.3) - 0.2.5.4 and 0.2.5.5 give me that above error.
I checked the line and it hasn't changed, so I am not sure why this is happening. I've cleared the build cache as well.

The log for web Dockerfile for fad311282b380e58e9ed9fdea27f0c3e67a7c7cc (0.2.5.3) is attached:
[plan-70713347-FRON-1.log](https://github.com/danswer-ai/danswer/files/13223812/plan-70713347-FRON-1.log)

**Comment by Weves** [comment]
Hmm, my first hunch is that this might have to do with our upgrade to NextJS 14. 

Do you have a `node_modules` or a `.next` folder in your `web` directory? If so, it might be worth trying to delete these with `rm -rf node_modules` / `rm -rf .next` and then re-starting things. 

Also, what's the exact cmd your using to start things up?

**Comment by voarsh2** [comment]
> Hmm, my first hunch is that this might have to do with our upgrade to NextJS 14.
 
> Do you have a `node_modules` or a `.next` folder in your `web` directory? If so, it might be worth trying to delete these with `rm -rf node_modules` / `rm -rf .next` and then re-starting things.

The directory is fully cleaned, so it'll be just what's in the code's repository, checking my branch against the tag, /web/ doesn't have .next or node_modules


> Also, what's the exact cmd your using to start things up?

It's just a simple docker build command in the /web directory against the Dockerfile (using buildx)

**Comment by Weves** [comment]
Any luck with the changes? Would love to hear what's going wrong and put any necessary fixes into the repo 🙏

**Comment by voarsh2** [comment]
Will update as soon as I can. I will look to re-try one of the newer tags tomorrow or so. :)

**Comment by voarsh2** [comment]
No change necessary on the REPO side. Indeed the nodejs update caused it.
