### ISSUE TITLE
Vespa: AVX2 requirment

### ISSUE THREAD

**Issue by voarsh2** [danswer-ai/danswer#697]
I have 5 server nodes, one of them is a more up to date CPU that has AVX2 support, however it is more memory constrained than the others.

I cannot run VESPA on the other nodes that have more memory because VESPA prints out  "ILLEGAL INSTRUCTION". I saw an issue on GitHub about it, and there's a version of PyTorch that works with AVX1 that Vespa had pinned for a version.

Was wondering if you guys were familiar and could help me get VESPA running on a version that doesn't need AVX2?

**Comment by alex-feel** [comment]
I've encountered an opposite message stating, "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags."

**Comment by voarsh2** [comment]
Hmm. I guess I am not alone in wanting AV1 support for Vespa? :)

**Comment by yuhongsun96** [comment]
We're using some very recent features from Vespa for hybrid-search. So downgrading Vespa will break the search, which is a very core component of Danswer :(

Sadly, I don't think there's too much to be done here, any chance you can get servers with AVX2?

You could also try your luck asking the folks over at Vespa, they're pretty responsive luckily.

**Comment by yuhongsun96** [comment]
Good news! We checked with the Vespa folks and they have an image that doesn't require AVX2:
you can swap `vespaengine/vespa:8.249.12` to `vespaengine/vespa-generic-intel-x86_64:8.251.23` in the docker compose or kubernetes files and redeploy. Let me know if this works for you!

**Comment by voarsh2** [comment]
I'm glad to hear this. I will give that a spin soon. My power hungry Sandy Bridge CPU's will definitely be a better fit RAM wise compared with my Ryzen system.

if it works out, maybe documenting this option if it's a viable option for those in a similar situation as me?

**Comment by voarsh2** [comment]
Thought I'd give the project another look now that there's some new documentation on GPT4ALL and FastChat (hopefully I can make use of local LLMs)...
Nice to see my Kubernetes changes merged. I noticed the Vespa engine changed, but I couldn't see any new vespa-generic-intel-x86_64 images for Vespa.

@yuhongsun96 
Any ideas if vespaengine/vespa:8.277.17 is absolutely required, or can I use the old vespaengine/vespa-generic-intel-x86_64:8.251.23 for now? Hoping Vespa can build a new image for non AVX2 machines........
