### ISSUE TITLE
How to configure GPT4ALL?

### ISSUE THREAD

**Issue by voarsh2** [danswer-ai/danswer#706]
I setup the following env vars (as per your docs):
```
  GEN_AI_MODEL_PROVIDER: gpt4all
  GEN_AI_MODEL_VERSION: ggml-model-gpt4all-falcon-q4_0.bin
  INTERNAL_MODEL_VERSION: gpt4all-chat-completion
```
But output from API server gives me:

```

2023-11-07T08:56:11.233517463Z   File "/app/danswer/direct_qa/llm_utils.py", line 84, in get_default_qa_model
2023-11-07T08:56:11.233547959Z     llm = get_default_llm(timeout=timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/llm/build.py", line 48, in get_default_llm
    raise ValueError(f"Unknown LLM model: {INTERNAL_MODEL_VERSION}")
2023-11-07T08:56:11.233950634Z ValueError: Unknown LLM model: gpt4all-chat-completion
```

It does in fact download the model, and I rebuilt the Dockerfile with gpt4all requirement.
Am I missing something?

Do I need to add these lines back in?
https://github.com/danswer-ai/danswer/pull/233/files#diff-cd54b37b2e4fe499ffd1a5acb2bb4545ab7c28cfd9c834b6c5a9483a528a93f4

I also get when it tries to use the GPT4ALL model
```
Segmentation fault (core dumped)
```

**Comment by yuhongsun96** [comment]
https://docs.danswer.dev/gen_ai_configs/gpt_4_all

Where are you seeing the INTERNAL_MODEL_VERSION. I think you may be referring to outdated docs. Please share where it is so I can correct it.

Also, ya the issue where GPT4ALL isn't supported on all platforms is sadly still around. So you'll have to add back the requirement and build the image https://github.com/danswer-ai/danswer/blob/main/backend/requirements/default.txt#L18.

https://docs.danswer.dev/quickstart (see build from source)

**Comment by voarsh2** [comment]
> https://docs.danswer.dev/gen_ai_configs/gpt_4_all
> Where are you seeing the INTERNAL_MODEL_VERSION. I think you may be referring to outdated docs. Please share where it is so I can correct it.

It complains about INTERNAL_MODEL_VERSION being blank - this is on my Kubernetes global env branch where values are blank.
I will also look to try and remember about the outdated docs.
 
> Also, ya the issue where GPT4ALL isn't supported on all platforms is sadly still around. So you'll have to add back the requirement and build the image https://github.com/danswer-ai/danswer/blob/main/backend/requirements/default.txt#L18.

As stated, I added back the requirement line for gpt4all.

> https://docs.danswer.dev/quickstart (see build from source)

**Comment by yuhongsun96** [comment]
Be sure you're on the latest version of the code as well. If you're still seeing INTERNAL_MODEL_VERSION, then you must be on a pretty old version

**Comment by voarsh2** [comment]
> Be sure you're on the latest version of the code as well. If you're still seeing INTERNAL_MODEL_VERSION, then you must be on a pretty old version

Yes, the branch is up-to-date.
Is ```INTERNAL_MODEL_VERSION``` even used?

**Comment by yuhongsun96** [comment]
It is no longer used, that's why I was wondering if you were on an old version. Is the new docs/environment settings for setting up GPT4All not working for you?

**Comment by voarsh2** [comment]
> It is no longer used, that's why I was wondering if you were on an old version. Is the new docs/environment settings for setting up GPT4All not working for you?

I just merged 0.2.65 into my branch. So you're saying ```INTERNAL_MODEL_VERSION``` is not used in v0.2.65, and I can remove this reference in https://github.com/danswer-ai/danswer/pull/515?

**Comment by yuhongsun96** [comment]
Ya `INTERNAL_MODEL_VERSION` is gone. You can refer to the [dev docker compose](https://github.com/danswer-ai/danswer/blob/main/deployment/docker_compose/docker-compose.dev.yml) for the most useful env variables

**Comment by voarsh2** [comment]
Perfect. Waiting for my build to build all the Dockerfile's and will test again against 0.2.65 tag using just:
```
GEN_AI_MODEL_PROVIDER=gpt4all
GEN_AI_MODEL_VERSION=mistral-7b-openorca.Q4_0.gguf
```

Will also update my PR to remove the unused env var.

**Comment by voarsh2** [comment]
I gave it another try.
I used the options you suggested:

```
GEN_AI_MODEL_PROVIDER=gpt4all
GEN_AI_MODEL_VERSION=mistral-7b-openorca.Q4_0.gguf
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 266, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(model=model, custom_llm_provider=custom_llm_provider, api_base=api_base)
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1644, in get_llm_provider
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1641, in get_llm_provider
    raise ValueError(f"LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/{model}',..)` Learn more: https://docs.litellm.ai/docs/providers")
ValueError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/gpt4all/mistral-7b-openorca.Q4_0.gguf',..)` Learn more: https://docs.litellm.ai/docs/providers
```

Something missing in the docs?

**Comment by voarsh2** [comment]
Any time to tell me how to get the local LLM in memory working?

**Comment by yuhongsun96** [comment]
Ah I found a bug, fixed it, please pull main and try again! Don't forget you have to install gpt4all in the container or your environment as we don't install the library by default due to issues with certain architectures

**Comment by voarsh2** [comment]
That issue has gone away, it seems, but I can't test it because ```mistral-7b-openorca.Q4_0.gguf``` doesn't seem to work on AVX1 CPU's? 
```
double free or corruption (!prev)
2023-11-29T23:32:50.100321020Z Aborted (core dumped)
```

I tried on AVX2 supported CPU but I don't have the memory on that node for 7B - it isn't a dedicated node just for Danswer. :/

**Comment by yuhongsun96** [comment]
You can probably try some smaller model? Also a lot of people have been liking Ollama, maybe that will work better, you can run Ollama somewhere and point Danswer to it.

I'm going to close the issue since it seems the problem is no longer with the Danswer portion of things. Best of luck!
