### ISSUE TITLE
Integration Support for GPT-4 Turbo and Updated GPT 3.5 Turbo Models

### ISSUE THREAD

**Issue by alex-feel** [danswer-ai/danswer#707]
I'd like to request the integration of the new GPT-4 Turbo (`gpt-4-1106-preview`) and Updated GPT 3.5 Turbo (`gpt-3.5-turbo-1106`) models as announced in [OpenAI's recent blog post](https://openai.com/blog/new-models-and-developer-products-announced-at-devday).

The current documentation for `litellm` mentions support for only `gpt-4-1106-preview`. It would be beneficial for us to support both models mentioned above. 

Please note, this might require an update of the `openai` module to incorporate bug fixes from [this PR](https://github.com/openai/openai-python/pull/694). However, the latest `litellm` package version 0.13.2 is compatible with up to `openai` package version 0.28.1, which should be taken into account to ensure compatibility is maintained.

**Comment by yuhongsun96** [comment]
Good suggestion, will look into it and also ask the LiteLLM folks

**Comment by photonn** [comment]
In Azure, gpt-4-1106-preview IS gpt-4 turbo. I'm using it with danswer without issues since a few weeks ago:

https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/azure-openai-service-launches-gpt-4-turbo-and-gpt-3-5-turbo-1106/ba-p/3985962

**Comment by yuhongsun96** [comment]
Yup, gpt-4-turbo has been supported for quite some time now, going to close this one now!
