### ISSUE TITLE
danswer-stack-index-1容器中出现错误

### ISSUE THREAD

**Issue by 2016g305** [danswer-ai/danswer#758]
docker desktop中运行danswer时，danswer-stack-index-1容器中出现错误，日志显示“023-11-22 20:33:47 /usr/local/bin/start-container.sh: line 67:    10 Illegal instruction     /opt/vespa/bin/vespa-start-configserver”。这个问题如何解决？

**Comment by yuhongsun96** [comment]
You must be using a CPU without avx2 instruction support.
You can use https://hub.docker.com/r/vespaengine/vespa-generic-intel-x86_64 instead
