### ISSUE TITLE
Minimum System Requirements

### ISSUE THREAD

**Issue by accforgithubtest** [danswer-ai/danswer#777]
For anyone looking to try this out on their own machines, it would be nice to know what the minimum system requirements are.
Perhaps this location would be a good place to specify it ?
https://docs.danswer.dev/quickstart#requirements

**Comment by yuhongsun96** [comment]
Hi! This is a great suggestion! We've added a page here: https://docs.danswer.dev/resourcing

We would love to hear from you about your use case and how Danswer has been performing for you! If you're open to it, we’d love to hear from you in our [Slack](https://join.slack.com/t/danswer/shared_invite/zt-1u3h3ke3b-VGh1idW19R8oiNRiKBYv2w) or [Discord](https://discord.gg/TDJ59cGV2X)! Alternatively if you want to have a quick chat with the maintainer (Chris and myself), you can just select a time on my [Cal](https://app.cal.com/yuhongsun)
