### ISSUE TITLE
Boost value is reset after each document update

### ISSUE THREAD

**Issue by mboret** [danswer-ai/danswer#787]
Hi,

After boosting a document, its boost score goes to 0 each time it is updated. It's annoying as we need to re-boost it each time.

Could you preserve the boost value from the document update?

Thanks!

**Comment by Weves** [comment]
Hey @mboret, thanks for pointing this out and sorry about the delay. 

This should now be fixed in https://github.com/danswer-ai/danswer/pull/864! 

Let me know if you are still running into any issues after pulling in the latest.
