### ISSUE TITLE
How does this compare to Amazon Q

### ISSUE THREAD

**Issue by jkfnc** [danswer-ai/danswer#790]
https://docs.aws.amazon.com/amazonq/latest/business-use-dg/connectors-list.html

**Comment by yuhongsun96** [comment]
Hi sorry for the really long delay on this, somehow it slipped through the cracks.

- Danswer has better/different chat features such as selecting documents on the fly.
- Danswer is open source => free, transparent, customizable, more maintainable
- Danswer allows you to choose LLMs of your choice including GPT-4 which is far better than the bedrock options
- Danswer is self-hosted, you can deploy it on any cloud of your choice or even on-prem
- You can use Danswer in Slack via a SlackBot

Overall, we're fairly confident our solution is more useable and better performing compared to Amazon Q.

We would love to hear from you about your use case and how Danswer has been performing for you! If you're open to it, we’d love to hear from you in our [Slack](https://join.slack.com/t/danswer/shared_invite/zt-1u3h3ke3b-VGh1idW19R8oiNRiKBYv2w) or [Discord](https://discord.gg/TDJ59cGV2X)! Alternatively if you want to have a quick chat with the maintainer (Chris and myself), you can just select a time on my [Cal](https://app.cal.com/yuhongsun)
