### ISSUE TITLE
Feature request: Allow basic auth in community edition

### ISSUE THREAD

**Issue by photonn** [danswer-ai/danswer#796]
Would be nice to use just basic auth (with users stored in postgres) for authentication against Danswer. I know that basic auth is supporte in the backend, but a UI page to create and delete users would be nice.

**Comment by evin-bz** [comment]
I'd love this as well.  To add some context, I have some pages behind a 1) firewall, and 2) oauth / token credential that I'd love to index.  Allowing folks to add something like a header, basicauth or a cooke to be passed in to those requests, would be fantastical! 

Tangentially - another option is to be able to restrict the scanning to a single file within the given adapters.  For example - the two files that I'm interested in indexing are a single file in github - so being able to pick a repo and JUST that file would be fantastic (same with like, the confluence connector)

**Comment by Weves** [comment]
Hey @photonn, just wanted to let you know that initial support for this is now in with https://github.com/danswer-ai/danswer/pull/879! This PR allows for signup, login, and email verification (see screenshot below for an idea of what it looks like). User deletion / a UI to control allowed emails / password reset to come!

![image](https://github.com/danswer-ai/danswer/assets/25087905/14579ef8-dfaa-4ac7-a44e-e38ab6748fed)

**Comment by yuhongsun96** [comment]
Closing as this is completed! Huzzah! One thing that is probably a necessary addition at some point for this is password reset. We have it on our radar.

@evin-bz we haven't gotten the chance to know you. We would love to hear from you about your use case and how Danswer has been performing for you! If you're open to it, we’d love to hear from you in our [Slack](https://join.slack.com/t/danswer/shared_invite/zt-1u3h3ke3b-VGh1idW19R8oiNRiKBYv2w) or [Discord](https://discord.gg/TDJ59cGV2X)! Alternatively if you want to have a quick chat with the maintainer (Chris and myself), you can just select a time on my [Cal](https://app.cal.com/yuhongsun)

**Comment by photonn** [comment]
Thank you all. Much apreciated.
