### ISSUE TITLE
error in process_model_tokens

### ISSUE THREAD

**Issue by klovec** [danswer-ai/danswer#814]
function `process_model_tokens()` in `qa_utils.py` 

```python
if not found_answer_start and '{"answer":"' in re.sub(r"\s", "", model_output):
            # Note, if the token that completes the pattern has additional text, for example if the token is "?
            # Then the chars after " will not be streamed, but this is ok as it prevents streaming the ? in the
            # event that the model outputs the UNCERTAINTY_PAT
            found_answer_start = True

            # Prevent heavy cases of hallucinations where model is not even providing a json until later
            if is_json_prompt and len(model_output) > 40:
                logger.warning("LLM did not produce json as prompted")
                found_answer_end = True

            continue
```
It is not appropriate to directly "continue" here, because there will be a stream return like the following example:

```
{"
answer
":
 "订单状态
....
```
This will result in missing content in the `answer_piece`.

**Comment by yuhongsun96** [comment]
I'm not sure what you mean. If the json is over multiple lines like {\n"answer": thenthe re.sub will take care of the newlines. I've never seen the model output "\nanswer\n". If the model is doing this then something is fairly wrong. In cases where the model is failing to produce the right keys, we chose not to show any outputs to the user. Please reopen if I am misinterpreting what you are saying, thanks!

**Comment by klovec** [comment]
@yuhongsun96 Sorry, my problem description is not clear enough.  and I am using a custom LLM model. 
What I mean is that the output result does not have the characters(`订单状态`) in line 4 after symbol "
```
1  {"
2  answer
3  ":
4   "订单状态
5  ....
```
Because there are no these characters in var "model_previous"
