### ISSUE TITLE
Add Baseurl config for GitHub connector

### ISSUE THREAD

**Issue by jonathonlacher** [danswer-ai/danswer#836]
Right now the Connector assumes the default base URL for the API. However for GitHub Enterprise installations, the base URL for the API is different: like `https://github.example.com/api/v3`.

It would be nice just to expose this as a config item.

**Comment by Weves** [comment]
Hey @jonathonlacher, thanks for pointing this out - adding this as a config totally makes sense. Happy to add it, should be a quick one.

For your org, would all relevant repos use the same base URL? I ask to see if this is something that makes the most sense as an env variable or a part of the connector config itself 🤔

**Comment by jonathonlacher** [comment]
For my use case I would likely just connect to a single base URL. However I could imagine situations where someone would want to connect both to their private enterprise GitHub server and also GitHub.com

**Comment by yuhongsun96** [comment]
Hello! I just added the ability to configure a base URL for GitHub with https://github.com/danswer-ai/danswer/pull/922 (I can't verify it end to end but it should work). If someone else needs multiple URLs, we'll extended it and provide a UI option.

We would love to hear from you about your use case and how Danswer has been performing for you! If you're open to it, we’d love to hear from you in our [Slack](https://join.slack.com/t/danswer/shared_invite/zt-1u3h3ke3b-VGh1idW19R8oiNRiKBYv2w) or [Discord](https://discord.gg/TDJ59cGV2X)! Alternatively if you want to have a quick chat with the maintainer (Chris and myself), you can just select a time on my [Cal](https://app.cal.com/yuhongsun)!
