### ISSUE TITLE
File connector: Support links via a metadata file in zip upload

### ISSUE THREAD

**Issue by sjakos** [danswer-ai/danswer#860]
To make it easier to add links to PDFs and other documents without modifying the files, I've modified the zip file loader to look for a `.danswer_metadata.json` file that has additional metadata about the files.

The `.danswer_metadata.json` file has a JSON object with the filenames as the keys, or an array of JSON objects with the filename as a value:
```json
[{"filename": "foo.pdf", "link": "https://example.com/foo.pdf"}]
```

**Comment by yuhongsun96** [comment]
This is a great idea! From your phrasing, it seems like you already have the implementation for this? Would you consider contributing it to the repo so others can benefit from it too? That would be really awesome!
