### ISSUE TITLE
Sweep: Do not start 

### ISSUE THREAD

**Issue by xxx1099836595** [danswer-ai/danswer#888]
### Details

![image](https://github.com/danswer-ai/danswer/assets/56339543/f3a958f5-b6b6-4721-8d2d-1828d937f7b8)

Some fetch failed for the main search page - TypeError: fetch failed
Error fetching user: TypeError: fetch failed
TypeError: Cannot read properties of null (reading 'authType')
    at w (/app/.next/server/app/search/page.js:18:3740)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '1036636207'
}

**Comment by rubabuddin** [comment]
seeing the same issue - related to this PR? https://github.com/danswer-ai/danswer/pull/879

**Comment by Weves** [comment]
Hey @xxx1099836595 and @rubabuddin, thanks for bringing this issue up. This should be fixed in https://github.com/danswer-ai/danswer/pull/884 + https://github.com/danswer-ai/danswer/pull/891 🙏 

Let me know if you run into any more issues here - will jump on it ASAP!
