### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS How to fix this error?

### ISSUE THREAD

**Issue by mkygogo** [danswer-ai/danswer#890]
### Details

Run the docker , when I try "http://localhost:3000/" I just got error: ERR_TOO_MANY_REDIRECTS 
How can I fix this ? tks

**Comment by Weves** [comment]
Hey @mkygogo, sorry about this issue. It should be fixed in https://github.com/danswer-ai/danswer/pull/884 + https://github.com/danswer-ai/danswer/pull/891 🙏

Let me know if you run into any more issues here - will jump on it ASAP!
