### ISSUE TITLE
Sweep: Can't have login page

### ISSUE THREAD

**Issue by harding13** [danswer-ai/danswer#925]
### Details

After installing, the web server container log had this

  ▲ Next.js 14.0.3
   - Local:        http://4eb125652e3b:3000
   - Network:      http://172.26.0.6:3000
 ✓ Ready in 90ms
Some fetch failed for the login page - TypeError: fetch failed
Error fetching user: TypeError: fetch failed

on the browser there was only the danswer logo

**Comment by harding13** [comment]
Solved. It was port conflict problem

**Comment by yuhongsun96** [comment]
Nice, glad you figured it out!

We would love to hear from you about your use case and how Danswer has been performing for you! If you're open to it, we’d love to hear from you in our [Slack](https://join.slack.com/t/danswer/shared_invite/zt-2afut44lv-Rw3kSWu6_OmdAXRpCv80DQ) or [Discord](https://discord.gg/TDJ59cGV2X)! Alternatively if you want to have a quick chat with the maintainer (Chris and myself), you can just select a time on my [Cal](https://app.cal.com/yuhongsun)
