### ISSUE TITLE
 The user is not being redirected to the correct page after successful registration, instead, a login window continues to appear. Is there a setting that is incorrect? I have already obtained the latest code.

### ISSUE THREAD

**Issue by huicewang** [danswer-ai/danswer#955]
The user is not being redirected to the correct page after successful registration, instead, a login window continues to appear. Is there a setting that is incorrect? I have already obtained the latest code.
![image](https://github.com/danswer-ai/danswer/assets/19237481/2c821ef7-981b-4380-aa10-67444ad9361c)

**Comment by huicewang** [comment]
After successful registration, the page also redirects to the login page.

**Comment by finitespace** [comment]
I am also having issues with this and cannot login

**Comment by Hewlbern** [comment]
Same issue as well

**Comment by regmibijay** [comment]
If you created the docker instances using `docker compose up` you need to delete volumes and force recreate after you change settings. Set `WEB_DOMAIN` to your chat interface in `.env` like `WEB_DOMAIN=https://chat.mydomain.com` and then recreate whole stack.

**Comment by marvasgit** [comment]
I have same problem, even if you disable email verification  or try to use -google_oauth  i have same error 
those are the logs from Be. i think they might be useful to fix
`INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     172.18.0.7:41684 - "GET /health HTTP/1.1" 200 OK
INFO:     172.18.0.7:60080 - "GET /health HTTP/1.1" 200 OK
INFO:     172.18.0.6:39336 - "GET /auth/type HTTP/1.1" 200 OK
INFO:     172.18.0.6:39352 - "GET /manage/me HTTP/1.1" 403 Forbidden
INFO:     172.18.0.7:60186 - "GET /health HTTP/1.1" 200 OK
INFO:     172.18.0.6:39336 - "GET /manage/me HTTP/1.1" 403 Forbidden
INFO:     172.18.0.6:39336 - "GET /auth/type HTTP/1.1" 200 OK
(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
02/26/2024 01:27:49 PM             users.py 186 : User 262940f4-916d-4d33-a68c-306a54522ff4 has registered.
INFO:     172.18.0.7:60196 - "POST /auth/register HTTP/1.1" 201 Created
INFO:     172.18.0.7:60208 - "POST /auth/login HTTP/1.1" 204 No Content
INFO:     172.18.0.6:41688 - "GET /auth/type HTTP/1.1" 200 OK
INFO:     172.18.0.6:41704 - "GET /manage/me HTTP/1.1" 403 Forbidden
INFO:     172.18.0.6:41708 - "GET /manage/indexing-status HTTP/1.1" 403 Forbidden
INFO:     172.18.0.6:41746 - "GET /secondary-index/get-embedding-models HTTP/1.1" 403 Forbidden
INFO:     172.18.0.6:41754 - "GET /query/valid-tags HTTP/1.1" 403 Forbidden
INFO:     172.18.0.6:41718 - "GET /persona HTTP/1.1" 403 Forbidden
INFO:     172.18.0.6:41732 - "GET /manage/document-set HTTP/1.1" 403 Forbidden
INFO:     172.18.0.7:46894 - "GET /health HTTP/1.1" 200 OK
INFO:     172.18.0.7:46902 - "POST /auth/login HTTP/1.1" 204 No Content
INFO:     172.18.0.7:46918 - "GET /health HTTP/1.1" 200 OK
`

**Comment by marvasgit** [comment]
![2024-02-26_16-15](https://github.com/danswer-ai/danswer/assets/10674179/2ccebfbb-b3a1-4511-8532-87fb2940acce)
1,2 is successful registration. 
3,4 login attempt.
5 is registration attempt with same username.

**Comment by regmibijay** [comment]
possible fix would be something along the lines

``` python3
# WEB_DOMAIN already imported 

cookie_transport = CookieTransport(
  cookie_max_age=SESSION_EXPIRE_TIME_SECONDS,
  cookie_secure=WEB_DOMAIN.startswith("https://")
)
``` 
thoughts?

**Comment by marvasgit** [comment]
> possible fix would be something along the lines
> 
> 
> 
> ``` python3
> 
> # WEB_DOMAIN already imported 
> 
> 
> 
> cookie_transport = CookieTransport(
> 
>   cookie_max_age=SESSION_EXPIRE_TIME_SECONDS,
> 
>   cookie_secure=WEB_DOMAIN.startswith("https://")
> 
> )
> 
> ``` 
> 
> thoughts?
> 
> 

This should be extracted as configuration, because if it's purely internal use why should i be forced to use https ?

**Comment by regmibijay** [comment]
That is the point, we only use secure cookies if you configured WEB_DOMAIN to start with `https` otherwise not. That will give you freedom of using any protocol as you want.

**Comment by marvasgit** [comment]
> That is the point, we only use secure cookies if you configured WEB_DOMAIN to start with `https` otherwise not. That will give you freedom of using any protocol as you want.
sry my bad. didnt follow it on the phone. 
its good solution.
