### ISSUE TITLE
 Does the open-source version not provide grouping and performance statistics features? Can this feature be made available? Thank you.

### ISSUE THREAD

**Issue by huicewang** [danswer-ai/danswer#977]
Does the open-source version not provide grouping and performance statistics features? Can this feature be made available? Thank you.

**Comment by Weves** [comment]
Unfortunately, those features are part of the enterprise edition of Danswer :( 

If you want to self-host Danswer with these additional features, please reach out to us on [Slack](https://join.slack.com/t/danswer/shared_invite/zt-2afut44lv-Rw3kSWu6_OmdAXRpCv80DQ) or [Discord](https://discord.gg/TDJ59cGV2X) and we'd be more than happy to chat! Alternatively if you want to have a quick chat with the maintainers (@yuhongsun96 and myself), you can select a time on my [Cal](https://app.cal.com/weves).
