### ISSUE TITLE
Slack bot integration dispatch_failed

### ISSUE THREAD

**Issue by rohitrsh** [danswer-ai/danswer#980]
Hello,

I am trying to integrate Danswer with our Slack instance, and I have an app created, as mentioned in the docs, and I have created a channel and invited a bot into that, in the log I can see in the backend server it has started the listener 

`2024-01-22 16:36:19,383 INFO spawned: 'slack_bot_listener' with pid 11
2024-01-22 16:37:19,403 INFO success: slack_bot_listener entered RUNNING state, process has stayed up for > than 60 seconds (startsecs)`

But when I am chatting with bot its giving me

`failed with the error "dispatch_failed"`

That is very generic response from Slack, I can't see any error message in the app, can anyone help me how I can troubleshoot it?

**Comment by rohitrsh** [comment]
This is fixed. I had to update the env-config and deploy the app; for some reason, it wasn't working for me when I added a token from the UI.

**Comment by elvis-cai** [comment]
same issue here, have to add in env config in k8s deployment

**Comment by bslavin** [comment]
Where is the env-config and what did you add?

**Comment by cpouldev** [comment]
this should be reopened because I'm facing the same issue too, but I'm evaluating the cloud version so no env-conf for me. The only way to add the token is via the UI

related https://github.com/onyx-dot-app/onyx/issues/1369
